// SPDX-License-Identifier: AGPL-3.0-only

package sso

// The Authentik blueprint templates. Each is a Go text/template rendered by
// BlueprintGenerator against a small value map, and each produces a YAML
// document Authentik's blueprint API accepts. They live together, apart from the
// generator, because reading a rendered blueprint means reading its template:
// the shape of what Bloud provisions into Authentik is declared here and nowhere
// else.
const oidcBlueprintTemplate = `# Authentik Blueprint for {{.DisplayName}}
# Auto-generated by Bloud host-agent from catalog SSO config
version: 1
metadata:
  name: {{.AppName}}-sso-blueprint
  labels:
    managed-by: bloud

entries:
  # OAuth2 Provider
  - model: authentik_providers_oauth2.oauth2provider
    id: {{.AppName}}-oauth2-provider
    identifiers:
      name: {{.DisplayName}} OAuth2 Provider
    attrs:
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      client_type: {{.ClientType}}
      client_id: {{.ClientID}}
{{- if .ClientSecret}}
      client_secret: {{.ClientSecret}}
{{- end}}
      redirect_uris:
{{- range .RedirectURIs}}
        - url: "{{.}}"
          matching_mode: strict
{{- end}}
      signing_key: !Find [authentik_crypto.certificatekeypair, [name, "authentik Self-signed Certificate"]]
      sub_mode: hashed_user_id
      include_claims_in_id_token: true
      access_code_validity: minutes=1
      access_token_validity: minutes=5
      refresh_token_validity: days=30
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-email]]
        - !Find [authentik_providers_oauth2.scopemapping, [managed, goauthentik.io/providers/oauth2/scope-profile]]

  # Application
  - model: authentik_core.application
    id: {{.AppName}}-application
    identifiers:
      slug: {{.AppName}}
    attrs:
      name: {{.DisplayName}}
      provider: !KeyOf {{.AppName}}-oauth2-provider
      policy_engine_mode: any
      group: ""
{{- if .LaunchURL}}
      meta_launch_url: "{{.LaunchURL}}"
{{- end}}
`

const forwardAuthBlueprintTemplate = `# Authentik Forward Auth Blueprint for {{.DisplayName}}
# Auto-generated by Bloud host-agent from catalog SSO config
version: 1
metadata:
  name: {{.AppName}}-sso-blueprint
  labels:
    managed-by: bloud

entries:
  # Proxy Provider for forward auth
  - model: authentik_providers_proxy.proxyprovider
    id: {{.AppName}}-proxy-provider
    identifiers:
      name: {{.DisplayName}} Proxy Provider
    attrs:
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      mode: forward_single
      external_host: "{{.ExternalHost}}"
      access_token_validity: minutes=5

  # Application
  - model: authentik_core.application
    id: {{.AppName}}-application
    identifiers:
      slug: {{.AppName}}
    attrs:
      name: {{.DisplayName}}
      provider: !KeyOf {{.AppName}}-proxy-provider
      policy_engine_mode: any
      group: ""
{{- if .LaunchURL}}
      meta_launch_url: "{{.LaunchURL}}"
{{- end}}
`

const outpostBlueprintTemplate = `# Authentik Embedded Outpost Configuration
# Auto-generated by Bloud host-agent
# This blueprint adds all Bloud forward-auth providers to the embedded outpost.
# It also configures authentik_host and authentik_host_browser for correct OAuth redirects.
# IMPORTANT: When using state: present with config, all config values must be specified
# as the entire config dict is replaced (not merged).
version: 1
metadata:
  name: bloud-outpost-providers
  labels:
    managed-by: bloud

entries:
  # Update the embedded outpost to include all Bloud forward-auth providers
  - model: authentik_outposts.outpost
    state: present
    identifiers:
      name: authentik Embedded Outpost
    attrs:
      providers:
{{- range .Providers}}
        - !Find [authentik_providers_proxy.proxyprovider, [name, "{{.DisplayName}} Proxy Provider"]]
{{- end}}
      config:
        # URL for outpost to communicate with authentik (internal)
        authentik_host: "{{.AuthentikURL}}"
        # Browser-accessible URL for OAuth redirects (critical for forward-auth)
        authentik_host_browser: "{{.AuthentikURL}}"
        log_level: info
`

// ldapAppBlueprintTemplate creates app-specific groups and an application entry for LDAP apps
const ldapAppBlueprintTemplate = `# Authentik LDAP Blueprint for {{.DisplayName}}
# Auto-generated by Bloud host-agent from catalog SSO config
# Creates app-specific groups for LDAP authorization
version: 1
metadata:
  name: {{.AppName}}-ldap-blueprint
  labels:
    managed-by: bloud

entries:
  # Group for regular users
  - model: authentik_core.group
    id: {{.AppName}}-users-group
    identifiers:
      name: {{.AppName}}-users

  # Group for admin users
  - model: authentik_core.group
    id: {{.AppName}}-admins-group
    identifiers:
      name: {{.AppName}}-admins

  # Application entry (for Authentik dashboard)
  - model: authentik_core.application
    id: {{.AppName}}-application
    identifiers:
      slug: {{.AppName}}
    attrs:
      name: {{.DisplayName}}
      policy_engine_mode: any
      group: ""
{{- if .LaunchURL}}
      meta_launch_url: "{{.LaunchURL}}"
{{- end}}
`

const ldapOutpostBlueprintTemplate = `# Authentik LDAP Provider and Outpost Configuration
# Auto-generated by Bloud host-agent
# This blueprint creates the LDAP infrastructure for apps that need LDAP authentication
# (e.g., Jellyfin for TV/mobile clients)
version: 1
metadata:
  name: bloud-ldap-provider
  labels:
    managed-by: bloud

entries:
  # LDAP Provider - enables LDAP protocol for Authentik users
  - model: authentik_providers_ldap.ldapprovider
    id: bloud-ldap-provider
    identifiers:
      name: Bloud LDAP Provider
    attrs:
      authorization_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      search_group: !Find [authentik_core.group, [name, authentik Admins]]
      bind_mode: direct
      search_mode: direct

  # Application for LDAP Provider (required - providers must be linked to an application)
  - model: authentik_core.application
    id: bloud-ldap-application
    identifiers:
      slug: ldap
    attrs:
      name: LDAP Authentication
      provider: !KeyOf bloud-ldap-provider
      policy_engine_mode: any
      group: ""

  # Service account for LDAP bind operations
  # Apps use this account to search/bind against LDAP
  - model: authentik_core.user
    id: ldap-service-account
    identifiers:
      username: ldap-service
    attrs:
      name: LDAP Service Account
      path: users
      type: service_account
      is_active: true

  # App password token for the service account
  # This is the password apps will use to bind to LDAP
  - model: authentik_core.token
    id: ldap-service-token
    identifiers:
      identifier: ldap-service-bind-token
    attrs:
      user: !KeyOf ldap-service-account
      intent: app_password
      expiring: false
      key: "{{.LDAPBindPassword}}"

  # LDAP Outpost - runs the LDAP server
  # Authentik auto-generates the API token (ak-outpost-{uuid}-api) when the outpost is created
  # The host-agent queries this token after blueprint application and passes it to the container
  - model: authentik_outposts.outpost
    id: bloud-ldap-outpost
    identifiers:
      name: Bloud LDAP Outpost
    attrs:
      name: Bloud LDAP Outpost
      type: ldap
      providers:
        - !KeyOf bloud-ldap-provider
      config:
        authentik_host: "{{.AuthentikURL}}"
        log_level: info
`
