// SPDX-License-Identifier: AGPL-3.0-only

package radicale

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"codeberg.org/d-buckner/bloud/services/host-agent/pkg/authentik"
	"codeberg.org/d-buckner/bloud/services/host-agent/pkg/configurator"
	"codeberg.org/d-buckner/bloud/services/host-agent/pkg/managedfile"
)

// The feed sync runs as a sidecar to Radicale rather than inside it.
//
// The previous implementation was a Python storage plugin vendored into the
// Radicale process, which meant the sync shared a lifetime, a failure domain,
// and a codebase with the server it fed. It also had to reach into the storage
// layer to create the collections it was filling, because nothing else could.
//
// pimsync talks to the running server over CalDAV the way any client does. It
// creates the collection it needs, it can be restarted without touching the
// server, and it is a maintained upstream rather than a fork.

const (
	// pimsyncNodeName is the sidecar's graph node. It is a node in its own
	// right because it is a separate container with its own lifecycle, and
	// because giving it a configurator is what lets its own PreStart render
	// its own config and report RestartNeeded, instead of the Radicale
	// configurator reaching across into another node's business.
	pimsyncNodeName = "apps-radicale-pimsync"

	// pimsyncConfigFileName is the rendered config. The name is pimsync's
	// own convention.
	pimsyncConfigFileName = "pimsync.conf"

	// pimsyncConfigDirName and pimsyncStatusDirName are the host-side
	// directories under the app's data tree. They are separate because one is
	// written by the host agent and read by the container, and the other is
	// written by the container.
	pimsyncConfigDirName = "pimsync"
	pimsyncStatusDirName = "pimsync-status"

	// The container-side mount points. The config is mounted at /etc/pimsync
	// rather than at the image's own /pimsync because that directory has to
	// stay writable: the image's startup script drops an example file into it.
	pimsyncContainerConfigDir = "/etc/pimsync"
	pimsyncContainerStatusDir = "/var/lib/pimsync/"

	// pimsyncStorageName is the name of the CalDAV target storage block: the
	// shared calendar account inside the Radicale this sidecar belongs to.
	pimsyncStorageName = "bloud"

	// pimsyncSyncIntervalSeconds is how often pimsync re-reads a feed it
	// cannot monitor. A webcal resource has no change notification, so this
	// is a poll. One hour matches what the plugin did and is plenty for
	// release calendars.
	pimsyncSyncIntervalSeconds = 3600
)

// pimsyncHeader is the banner atop every rendered config. It is the only
// thing telling a human who opens the file that editing it is futile.
const pimsyncHeader = `# Generated by Bloud. Do not edit: every reconciliation pass rewrites this
# file from the app catalog and the installed feed providers, and a local
# change is silently reverted.

`

// scfgQuote renders a value for a scfg configuration file.
//
// scfg is the format pimsync reads. A bare token may not contain a quote, a
// brace, or a control character, and a backslash inside one escapes the next
// character; a double-quoted string behaves the same but tolerates the
// characters a generated password or a feed URL might actually contain. So
// everything is quoted, and the two characters that need escaping are escaped.
//
// Note that scfg has no escape for a newline: `\n` is a literal `n`. Control
// characters are rejected outright rather than silently mangled, which is why
// a value containing one is refused here instead of being written anyway.
func scfgQuote(value string) (string, error) {
	if strings.ContainsAny(value, "\n\r\t") || strings.ContainsFunc(value, func(r rune) bool {
		return r < 0x20
	}) {
		return "", fmt.Errorf("value contains a control character and cannot be written to a scfg config")
	}
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range value {
		switch r {
		case '\\', '"':
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	b.WriteByte('"')
	return b.String(), nil
}

// pimsyncTarget is the CalDAV side every feed is projected into.
type pimsyncTarget struct {
	URL      string
	Username string
	Password string
}

// complete reports whether the target can be written to. Without the owner's
// credential there is nothing to sync into, and the right answer is to render
// a config with no pairs rather than one that fails on every connection.
func (t pimsyncTarget) complete() bool {
	return t.URL != "" && t.Username != "" && t.Password != ""
}

// renderPimsyncConf renders the whole config file.
//
// Each feed becomes one read-only webcal storage and one one-way pair that
// pushes it into the target. one_way is the whole point of that pairing: the
// feed is a projection of somebody else's system, so a change on the target
// side is not a conflict to resolve but a drift to overwrite, and items added
// on the target that the feed does not have are removed. That is exactly the
// semantics a synced feed should have, and it means the sync never produces a
// conflict nobody is around to resolve.
//
// A target without a credential renders no pairs. The sidecar then parks
// rather than crash-looping, and starts as soon as a later pass has something
// real to sync.
func renderPimsyncConf(target pimsyncTarget, feeds []configurator.ICSFeedBinding) (string, error) {
	var b strings.Builder
	b.WriteString(pimsyncHeader)

	statusPath, err := scfgQuote(pimsyncContainerStatusDir)
	if err != nil {
		return "", fmt.Errorf("status path: %w", err)
	}
	fmt.Fprintf(&b, "status_path %s\n", statusPath)

	if !target.complete() {
		return b.String(), nil
	}

	if err := writeTargetStorage(&b, target); err != nil {
		return "", err
	}
	for _, feed := range sortedFeeds(feeds) {
		if err := writeFeedBlocks(&b, feed); err != nil {
			return "", err
		}
	}
	return b.String(), nil
}

func writeTargetStorage(b *strings.Builder, target pimsyncTarget) error {
	url, err := scfgQuote(target.URL)
	if err != nil {
		return fmt.Errorf("target url: %w", err)
	}
	user, err := scfgQuote(target.Username)
	if err != nil {
		return fmt.Errorf("target username: %w", err)
	}
	pass, err := scfgQuote(target.Password)
	if err != nil {
		return fmt.Errorf("target password: %w", err)
	}
	fmt.Fprintf(b, "\nstorage %s {\n", pimsyncStorageName)
	b.WriteString("    type caldav\n")
	fmt.Fprintf(b, "    url %s\n", url)
	// `collections` skips the RFC 6764 discovery dance: the URL already names
	// the container we want, and inside a container network a DNS SRV lookup
	// is not a thing that should be happening anyway.
	b.WriteString("    discovery collections\n")
	fmt.Fprintf(b, "    username %s\n", user)
	fmt.Fprintf(b, "    password %s\n", pass)
	b.WriteString("}\n")
	return nil
}

func writeFeedBlocks(b *strings.Builder, feed configurator.ICSFeedBinding) error {
	name := feed.App
	url, err := scfgQuote(feedURL(feed))
	if err != nil {
		return fmt.Errorf("feed %s url: %w", name, err)
	}
	collID, err := scfgQuote(name)
	if err != nil {
		return fmt.Errorf("feed %s collection id: %w", name, err)
	}

	fmt.Fprintf(b, "\nstorage %s {\n", name)
	b.WriteString("    type webcal\n")
	fmt.Fprintf(b, "    url %s\n", url)
	// A webcal resource is one anonymous ICS document with no name of its
	// own, so the id it maps to on the CalDAV side has to be stated.
	fmt.Fprintf(b, "    collection_id %s\n", collID)
	fmt.Fprintf(b, "    interval %d\n", pimsyncSyncIntervalSeconds)
	b.WriteString("}\n")

	fmt.Fprintf(b, "\npair %s {\n", name)
	// The two storages are references to declared block names, so they stay
	// bare; the collection is a value, so it gets the same treatment as every
	// other value in this file.
	fmt.Fprintf(b, "    storage_a %s\n", name)
	fmt.Fprintf(b, "    storage_b %s\n", pimsyncStorageName)
	fmt.Fprintf(b, "    collection %s\n", collID)
	b.WriteString("    one_way\n")
	b.WriteString("}\n")
	return nil
}

// PimsyncConfigurator owns the feed-sync sidecar node.
//
// It has no container handle and makes no API calls: its whole job is to put
// a file on disk and say whether the container has to be recreated to pick it
// up. That is the shape most Bloud configurators have, and it is deliberate:
// the orchestrator owns the container, so a configurator that also owned it
// would be two writers.
type PimsyncConfigurator struct {
	logger *slog.Logger

	// secrets reads this app's own secret scope, which is where the
	// shared-calendar owner credential lands. Nil in tests and CLI runs;
	// that reads as "not yet", which renders a parked config.
	secrets configurator.AppSecretsProvider
}

// NewPimsyncConfigurator builds the sidecar's configurator from host Deps.
func NewPimsyncConfigurator(deps configurator.Deps) *PimsyncConfigurator {
	logger := deps.Logger
	if logger == nil {
		logger = slog.Default()
	}
	return &PimsyncConfigurator{
		logger:  logger.With("app", pimsyncNodeName),
		secrets: deps.Secrets,
	}
}

// Name returns the graph node this configurator drives.
func (c *PimsyncConfigurator) Name() string {
	return pimsyncNodeName
}

// PreStart lays out the two directories and writes the config.
//
// The status directory needs the same treatment Radicale's storage tree
// gets: the container runs as its own uid (1000 in this image), which under
// rootless podman is a subordinate uid the host agent is not and cannot
// become. The agent cannot hand the directory over by chowning it, so it
// opens it instead.
func (c *PimsyncConfigurator) PreStart(
	_ context.Context, state *configurator.AppState,
) (configurator.PreStartResult, error) {
	if state == nil || state.DataPath == "" {
		return configurator.NoRestart(), nil
	}

	configDir := filepath.Join(state.DataPath, pimsyncConfigDirName)
	statusDir := filepath.Join(state.DataPath, pimsyncStatusDirName)
	for _, dir := range []string{configDir, statusDir} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return configurator.NoRestart(), fmt.Errorf("create %s: %w", dir, err)
		}
	}
	if err := managedfile.EnsureWritable(statusDir, 0o777); err != nil {
		return configurator.NoRestart(), fmt.Errorf("open %s for the container user: %w", statusDir, err)
	}

	desired, err := renderPimsyncConf(c.target(), feedsOf(state))
	if err != nil {
		return configurator.NoRestart(), fmt.Errorf("render %s: %w", pimsyncConfigFileName, err)
	}

	path := filepath.Join(configDir, pimsyncConfigFileName)
	// ModeSharedConfig because the reader is the container process, which is
	// not the host uid that wrote the file. The credential in it is bounded
	// by the app's own data tree, which is the same boundary the LDAP reader
	// secret and the feed keys already sit behind.
	changed, err := managedfile.Write(path, []byte(desired), managedfile.ModeSharedConfig)
	if err != nil {
		return configurator.NoRestart(), fmt.Errorf("write %s: %w", path, err)
	}
	if !changed {
		return configurator.NoRestart(), nil
	}

	c.logger.Info("wrote pimsync config", "path", path)
	return configurator.MustRestart("pimsync config rewritten"), nil
}

// PostStart has nothing to verify.
//
// The sidecar's useful state is the sync itself, which happens on pimsync's
// own schedule and is visible as events appearing in the target collections
// -- asserted end-to-end by the aggregation integration test rather than
// re-derived here from a file this configurator wrote.
func (c *PimsyncConfigurator) PostStart(_ context.Context, _ *configurator.AppState) error {
	return nil
}

// target composes the CalDAV target from what the configurator can see: the
// sibling container's address, and the shared-calendar owner's credential.
func (c *PimsyncConfigurator) target() pimsyncTarget {
	return pimsyncTarget{
		URL:      fmt.Sprintf("http://%s:%d/%s/", nodeName, defaultPort, calendarOwner),
		Username: calendarOwner,
		Password: c.ownerPassword(),
	}
}

// ownerPassword reads the shared-calendar owner credential out of this app's
// secret scope. The Authentik configurator publishes it there during its own
// convergence, which is ordered before this node is reached.
func (c *PimsyncConfigurator) ownerPassword() string {
	if c.secrets == nil {
		return ""
	}
	return c.secrets.GetAppSecret(appName, authentik.CalendarOwnerSecretKey)
}
