{ config, pkgs, lib, ... }:

let
  appCfg = config.bloud.apps.authentik;
  bloudCfg = config.bloud;
  traefikCfg = config.bloud.apps.traefik;
  mkPodmanService = import ../../nixos/lib/podman-service.nix { inherit pkgs lib; };
  # Note: App-specific blueprints are now generated by the host-agent from metadata.yaml SSO config

  userHome = "/home/${bloudCfg.user}";
  configPath = "${userHome}/.local/share/${bloudCfg.dataDir}";

  # Shared postgres credentials (same as apps-postgres)
  postgresUser = "apps";
  postgresPassword = "testpass123";
  postgresDb = "authentik";
in
{
  options.bloud.apps.authentik = {
    enable = lib.mkEnableOption "Authentik SSO";

    port = lib.mkOption {
      type = lib.types.int;
      default = 9001;
      description = "Port to expose Authentik on";
    };

    httpsPort = lib.mkOption {
      type = lib.types.int;
      default = 9443;
      description = "HTTPS port for Authentik";
    };

    secretKey = lib.mkOption {
      type = lib.types.str;
      default = "test-secret-key-change-in-production-min-50-chars-long";
      description = "Authentik secret key (min 50 characters)";
    };

    bootstrapPassword = lib.mkOption {
      type = lib.types.str;
      default = "password";
      description = "Bootstrap admin password";
    };

    bootstrapEmail = lib.mkOption {
      type = lib.types.str;
      default = "admin@localhost";
      description = "Bootstrap admin email";
    };

    bootstrapToken = lib.mkOption {
      type = lib.types.str;
      default = "test-bootstrap-token-change-in-production";
      description = "Bootstrap API token";
    };
  };

  config = lib.mkIf appCfg.enable {
    # Ensure shared infrastructure is enabled
    bloud.apps.postgres.enable = true;
    bloud.apps.redis.enable = true;

    # Create Authentik directories
    system.activationScripts.bloud-authentik-dirs = lib.stringAfter [ "users" ] ''
      mkdir -p ${configPath}/{authentik-media,authentik-templates,authentik-certs,authentik-blueprints}
      mkdir -p ${configPath}/traefik/dynamic
      chown -R ${bloudCfg.user}:users ${configPath}/authentik-*
    '';

    # Copy Bloud brand blueprint (logo/favicon served from main UI /images/)
    system.activationScripts.bloud-authentik-branding = lib.stringAfter [ "bloud-authentik-dirs" ] ''
      cp ${./branding/bloud-brand.yaml} ${configPath}/authentik-blueprints/bloud-brand.yaml
      chown ${bloudCfg.user}:users ${configPath}/authentik-blueprints/bloud-brand.yaml
    '';

    # Extract Traefik routes from metadata.yaml (enables iframe embedding for SSO flows)
    system.activationScripts.bloud-authentik-traefik = lib.stringAfter [ "bloud-authentik-dirs" ] ''
      ${pkgs.yq-go}/bin/yq '.traefikConfig' ${./metadata.yaml} > ${configPath}/traefik/dynamic/authentik.yml
      chown ${bloudCfg.user}:users ${configPath}/traefik/dynamic/authentik.yml
    '';

    # Note: App-specific blueprints (actual-budget, miniflux, etc.) are now generated
    # by the host-agent from each app's metadata.yaml SSO config

    systemd.user.services = {
      # Database initialization for Authentik (creates database in shared postgres)
      authentik-db-init = {
        description = "Initialize Authentik database";
        after = [ "podman-apps-postgres.service" ];
        requires = [ "podman-apps-postgres.service" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = pkgs.writeShellScript "authentik-db-init" ''
            # Wait for postgres to be ready
            for i in {1..30}; do
              if ${pkgs.podman}/bin/podman exec apps-postgres psql -U ${postgresUser} -d ${postgresUser} -c "SELECT 1" &>/dev/null; then
                break
              fi
              echo "Waiting for postgres... ($i/30)"
              sleep 1
            done

            # Create database if it doesn't exist
            ${pkgs.podman}/bin/podman exec apps-postgres psql -U ${postgresUser} -c "CREATE DATABASE ${postgresDb};" 2>/dev/null || true
            ${pkgs.podman}/bin/podman exec apps-postgres psql -U ${postgresUser} -c "GRANT ALL PRIVILEGES ON DATABASE ${postgresDb} TO ${postgresUser};" || true
            echo "Authentik database ready"
          '';
        };
      };

      # Authentik Server
      podman-apps-authentik-server = mkPodmanService {
        name = "apps-authentik-server";
        image = "ghcr.io/goauthentik/server:2025.10.3";
        ports = [
          "${toString appCfg.port}:9000"
          "${toString appCfg.httpsPort}:9443"
        ];
        cmd = [ "server" ];
        environment = {
          AUTHENTIK_SECRET_KEY = appCfg.secretKey;
          AUTHENTIK_REDIS__HOST = "apps-redis";
          # Use shared postgres
          AUTHENTIK_POSTGRESQL__HOST = "apps-postgres";
          AUTHENTIK_POSTGRESQL__USER = postgresUser;
          AUTHENTIK_POSTGRESQL__NAME = postgresDb;
          AUTHENTIK_POSTGRESQL__PASSWORD = postgresPassword;
          AUTHENTIK_ERROR_REPORTING__ENABLED = "false";
          AUTHENTIK_BOOTSTRAP_PASSWORD = appCfg.bootstrapPassword;
          AUTHENTIK_BOOTSTRAP_EMAIL = appCfg.bootstrapEmail;
          AUTHENTIK_BOOTSTRAP_TOKEN = appCfg.bootstrapToken;
          # Enable blueprint discovery
          AUTHENTIK_BLUEPRINTS_DIR = "/blueprints";
          # External host for OAuth redirects (goes through Traefik for iframe headers)
          AUTHENTIK_HOST = "http://localhost:${toString traefikCfg.port}";
          AUTHENTIK_HOST_BROWSER = "http://localhost:${toString traefikCfg.port}";
        };
        volumes = [
          "${configPath}/authentik-media:/media:z"
          "${configPath}/authentik-templates:/templates:z"
          # Mount custom blueprints alongside default ones (don't replace /blueprints entirely)
          "${configPath}/authentik-blueprints:/blueprints/custom:z"
        ];
        network = "apps-net";
        dependsOn = [ "apps-network" "apps-postgres" "apps-redis" ];
        userns = "keep-id";
        # bloud-db-init creates the host-agent database (needed by prestart hook)
        # authentik-db-init creates the authentik database (needed by server)
        extraAfter = [ "bloud-db-init.service" "authentik-db-init.service" ];
        extraRequires = [ "bloud-db-init.service" "authentik-db-init.service" ];
        waitFor = [
          { container = "apps-postgres"; command = "pg_isready -U ${postgresUser}"; }
          { container = "apps-redis"; command = "redis-cli ping"; }
        ];
        # Wire up configurator to run after container starts (sets admin password, etc.)
        bloudAppName = "authentik";
        bloudAgentPath = bloudCfg.agentPath;
      };

      # Authentik Worker
      podman-apps-authentik-worker = mkPodmanService {
        name = "apps-authentik-worker";
        image = "ghcr.io/goauthentik/server:2025.10.3";
        cmd = [ "worker" ];
        environment = {
          AUTHENTIK_SECRET_KEY = appCfg.secretKey;
          AUTHENTIK_REDIS__HOST = "apps-redis";
          # Use shared postgres
          AUTHENTIK_POSTGRESQL__HOST = "apps-postgres";
          AUTHENTIK_POSTGRESQL__USER = postgresUser;
          AUTHENTIK_POSTGRESQL__NAME = postgresDb;
          AUTHENTIK_POSTGRESQL__PASSWORD = postgresPassword;
          AUTHENTIK_ERROR_REPORTING__ENABLED = "false";
        };
        volumes = [
          "${configPath}/authentik-media:/media:z"
          "${configPath}/authentik-templates:/templates:z"
          "${configPath}/authentik-certs:/certs:z"
          # Worker needs access to blueprints for discovery
          "${configPath}/authentik-blueprints:/blueprints/custom:z"
        ];
        network = "apps-net";
        dependsOn = [ "apps-network" "apps-postgres" "apps-redis" ];
        userns = "keep-id";
        # bloud-db-init creates the host-agent database (needed by prestart hook)
        # authentik-db-init creates the authentik database (needed by worker)
        extraAfter = [ "bloud-db-init.service" "authentik-db-init.service" ];
        extraRequires = [ "bloud-db-init.service" "authentik-db-init.service" ];
        waitFor = [
          { container = "apps-postgres"; command = "pg_isready -U ${postgresUser}"; }
          { container = "apps-redis"; command = "redis-cli ping"; }
        ];
      };

      # Authentik nginx proxy (adds X-Forwarded-Host header for correct OAuth URLs)
      podman-apps-authentik-proxy = mkPodmanService {
        name = "apps-authentik-proxy";
        image = "nginx:alpine";
        volumes = [
          "${configPath}/authentik-proxy.conf:/etc/nginx/conf.d/default.conf:ro"
        ];
        network = "apps-net";
        dependsOn = [ "apps-network" "apps-authentik-server" ];
      };
    };

    # Create nginx proxy config for Authentik
    # NOTE: We intentionally do NOT set X-Forwarded-Host here.
    # This allows Authentik to return URLs with the actual Host header.
    # - When accessed via Traefik (browser): Traefik sets X-Forwarded-Host → localhost:8080 URLs
    # - When accessed via apps-authentik-proxy (container): Host is apps-authentik-proxy → internal URLs
    # This is critical for server-to-server OAuth token exchange from containers.
    system.activationScripts.bloud-authentik-proxy-config = lib.stringAfter [ "bloud-authentik-dirs" ] ''
      cat > ${configPath}/authentik-proxy.conf <<'EOF'
server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://apps-authentik-server:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
EOF
      chown ${bloudCfg.user}:users ${configPath}/authentik-proxy.conf
    '';
  };
}
