// SPDX-License-Identifier: AGPL-3.0-only

package affine

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"

	"codeberg.org/d-buckner/bloud/services/host-agent/pkg/configurator"
	"codeberg.org/d-buckner/bloud/services/host-agent/pkg/managedfile"
)

const appName = "affine"

// The configurator creates AFFiNE's first user (the server admin) through the
// first-run setup endpoint before any SSO user exists, because until a first
// user exists every AFFiNE request redirects to /admin/setup and would block
// all end users.
//
// The email is the operator's SSO identity (deps.OperatorEmail, the Authentik
// admin email), not a synthetic Bloud account. AFFiNE links an OIDC login to an
// existing account by email, so when the operator signs in through Bloud's SSO
// they land on this account: they are the AFFiNE server admin, the workspace
// the configurator wires (the AI profile and the shared workspace) is theirs,
// and no manual workspace setup is needed. The password is generated by the secrets provider and never shared;
// the operator authenticates through SSO, not with it.
const (
	// The domain must carry a TLD: AFFiNE validates the address with zod's
	// default email regex, which rejects single-label domains like
	// "localhost". affine.localhost is the app's own (unroutable-elsewhere)
	// internal domain.
	fallbackAdminEmail = "bloud-admin@affine.localhost"
	bootstrapAdminName = "Bloud Admin"
)

// configFileName is the AFFiNE application config file written in PreStart
// and mounted into the server container at /root/.affine/config/config.json.
const configFileName = "config.json"

// sharedWorkspaceName is the name the one workspace Bloud creates carries.
// Bloud's model for AFFiNE is a single workspace the whole instance shares,
// not one per account, so the name says what it is rather than who made it.
const sharedWorkspaceName = "shared"

// workspaceInitDoc is the minimal Yjs root document AFFiNE expects for a
// workspace: a `meta` map with a name and an empty `pages` array. Without it,
// a server-created workspace is "uninitialized" and the editor spins on
// "Syncing..." without ever rendering its sidebar, so the AI chat entry never
// appears. The bytes were generated once with a fixed Yjs client id and
// round-tripped through yjs (they decode to {"name":"shared","pages":[]}).
//
// The name lives in this document and nowhere else the API can reach. AFFiNE's
// `WorkspaceType` has no `name` field, and the mutation that would set one,
// `adminUpdateWorkspace`, is behind an `assertCloudOnly()` guard that 404s on
// self-host. So the name is fixed at creation, by these bytes, and an existing
// workspace cannot be renamed by Bloud: it renames its own doc in the client.
var workspaceInitDoc = []byte{
	0x01, 0x02, 0x01, 0x00, 0x28, 0x01, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x01, 0x77, 0x06, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x27, 0x01, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x05, 0x70, 0x61, 0x67, 0x65, 0x73, 0x00, 0x00,
}

// csrfCookieName is the cookie AFFiNE pairs with the session and requires
// echoed back in the `x-csrf-token` header on every GraphQL write.
const csrfCookieName = "affine_csrf_token"

// Configurator handles AFFiNE configuration: it writes the application
// config (public URL + OIDC provider) before the server starts (PreStart),
// bootstraps the first-run owner account, and verifies the OIDC login
// round-trip is wired up after the server starts (PostStart). The bootstrapped
// account carries the operator's SSO identity email, so the operator's OIDC
// login links to it (AFFiNE links by email) and the wired workspace is theirs.
type Configurator struct {
	port       int
	ssoBaseURL func() string // current Bloud base URL (host-set aware; read on every PreStart)
	secrets    configurator.AppSecretsProvider
	adminEmail string // the operator's SSO identity email; first-user account + every sign-in use it
	logger     *slog.Logger
	api        *affineAPI

	// baseURL is a test seam: when set, the API client resolves to it
	// instead of localhost:port. Never used to build request URLs by hand.
	baseURL string
}

// NewConfigurator creates a new AFFiNE configurator from the host Deps.
// deps.PrimaryBaseURL supplies the current Bloud base URL (e.g.
// "http://localhost:8080"); the app's public URL is derived from it the same
// way routes and OIDC redirect URIs are (affine.<host>). It is a function so
// host changes made in the UI take effect without re-registering.
func NewConfigurator(port int, deps configurator.Deps) *Configurator {
	if port == 0 {
		port = defaultPort
	}
	logger := deps.Logger
	if logger == nil {
		logger = slog.Default()
	}
	adminEmail := deps.OperatorEmail
	if adminEmail == "" {
		adminEmail = fallbackAdminEmail
	}
	c := &Configurator{
		port:       port,
		ssoBaseURL: deps.PrimaryBaseURL,
		secrets:    deps.Secrets,
		adminEmail: adminEmail,
		logger:     logger.With("app", "affine"),
	}
	c.api = newAPI(deps.HTTP, func() string {
		if c.baseURL != "" {
			return c.baseURL
		}
		return fmt.Sprintf("http://localhost:%d", c.port)
	})
	return c
}

// nodeName is this app's graph node and container name; see NodeLifecycle.Name.
const nodeName = "apps-affine"

// defaultPort is the app's own web port, the value the constructor uses
// when registration passes 0. It matches metadata.yaml's `port`.
const defaultPort = 3010

func (c *Configurator) Name() string {
	return nodeName
}

// appExternalURL returns the public URL the browser uses to reach AFFiNE,
// e.g. "http://affine.localhost:8080". It must match the OIDC redirect URI
// base registered by the host-agent (app subdomain + callbackPath).
func (c *Configurator) appExternalURL() string {
	return configurator.AppExternalURL(c.ssoBaseURL, appName)
}

// PreStart writes the AFFiNE config file so the server comes up with the
// correct public URL and OIDC provider on the very first boot. Returns
// configChanged=true when the file content changed so the orchestrator
// recreates the container.
func (c *Configurator) PreStart(_ context.Context, state *configurator.AppState) (configurator.PreStartResult, error) {
	path := filepath.Join(state.DataPath, "config", configFileName)
	content, err := renderConfigFile(c.appExternalURL(), state.OIDC)
	if err != nil {
		return configurator.NoRestart(), err
	}
	changed, err := managedfile.Write(path, []byte(content), managedfile.ModeHostOnly)
	if err != nil {
		return configurator.NoRestart(), fmt.Errorf("writing config file: %w", err)
	}
	if changed {
		c.logger.Info("wrote AFFiNE config file", "path", path, "sso", state.OIDC != nil)
	}
	return configurator.RestartIf(changed, "AFFiNE config file rewritten"), nil
}

// PostStart verifies the server answers, creates the first-run owner
// account when the instance is uninitialized, and (when SSO is configured)
// verifies the OIDC provider is live: a preflight request must return the
// authorization URL, which proves config.json loaded, issuer discovery
// succeeded, and the PKCE flow is ready. Idempotent on every reconciliation.
func (c *Configurator) PostStart(ctx context.Context, state *configurator.AppState) error {
	if err := c.api.waitServer(ctx); err != nil {
		return fmt.Errorf("waiting for affine server: %w", err)
	}

	if err := c.ensureBootstrapAdmin(ctx); err != nil {
		return fmt.Errorf("bootstrapping owner account: %w", err)
	}

	c.publishAppAPICredential()

	c.ensureSharedWorkspace(ctx)

	c.ensureInferenceProvider(ctx, state)

	c.ensureSharedMembers(ctx, state)

	if state.OIDC == nil {
		return nil
	}
	if err := c.api.waitForOIDCPreflight(ctx); err != nil {
		return fmt.Errorf("verifying OIDC provider: %w", err)
	}
	c.logger.Info("OIDC login flow verified", "issuer", state.OIDC.IssuerURL)
	return nil
}

// ensureBootstrapAdmin creates the first-run owner account when the instance
// is uninitialized. AFFiNE only accepts the call before any user exists and
// answers "First user already created" otherwise, which is the idempotency
// signal for subsequent reconciliation passes.
func (c *Configurator) ensureBootstrapAdmin(ctx context.Context) error {
	if c.secrets == nil {
		return fmt.Errorf("no secrets provider")
	}
	password, err := c.secrets.GenerateAppAdminPassword(appName)
	if err != nil {
		return fmt.Errorf("generating admin password: %w", err)
	}

	changed, err := c.api.ensureOwner(ctx, bootstrapAdminName, c.adminEmail, password)
	if err != nil {
		return err
	}
	if changed {
		c.logger.Info("owner account created")
	}
	return nil
}

// --- appApi provider ---

// publishAppAPICredential hands a companion the account it signs in with when
// it cannot join the identity provider.
//
// AFFiNE removed its personal-access-token API in 0.27, so the only credential
// its GraphQL surface still validates is an account password. This publishes
// the bootstrap owner's, the same account the configurator itself signs in
// with, so a companion MCP server can call AFFiNE's API on the instance's
// behalf. The username is a value rather than a secret because it is visible in
// AFFiNE's own UI; the password is the credential.
//
// Idempotent: the stored password and username do not change across passes, and
// both setters no-op when the value already matches.
//
// Failures are logged and swallowed for the same reason the MCP credential's
// are: the node is the knowledge base itself, and a node that serves its users
// must not land in ERROR because an add-on credential could not be published. A
// consumer that required the secret receives an empty password and writes
// nothing rather than an empty credential.
//
// This publishes only the credential half. The workspace scope is published
// from ensureSharedWorkspace, which is where the shared workspace is settled;
// see there for why it is not published alongside the password.
func (c *Configurator) publishAppAPICredential() {
	if c.secrets == nil {
		c.logger.Warn("cannot publish the affine appApi credential: no secrets provider")
		return
	}
	password, err := c.secrets.GenerateAppAdminPassword(appName)
	if err != nil {
		c.logger.Warn("cannot publish the affine appApi credential: no owner password", "err", err)
		return
	}
	if err := c.secrets.SetAppSecret(appName, "password", password); err != nil {
		c.logger.Warn("affine appApi: could not publish the password", "err", err)
		return
	}
	if err := c.secrets.SetAppContractValue(appName, "appApi", "username", c.adminEmail); err != nil {
		c.logger.Warn("affine appApi: could not publish the username", "err", err)
	}
}

// --- Shared workspace ---

// ensureSharedWorkspace settles the one AFFiNE workspace Bloud works in and
// publishes its id to appApi companions.
//
// AFFiNE's own MCP server is not used (its endpoint is read-only and narrow;
// `apps/affine-mcp` provides the `mcp` contract instead), but the workspace is
// still load-bearing: it is what the BYOK AI profile is registered against and
// what the membership pass invites Bloud users into. A companion that cannot
// join the identity provider pins its default scope to the same id, so its
// tools address the workspace Bloud owns.
//
// Failures are logged and swallowed rather than returned. The node is the
// knowledge base itself, and a node that serves its users fine should not land
// in ERROR because a companion-facing value could not be published. The
// companion is protected regardless: a missing scope reads as "not pinned", not
// as an empty scope, and it falls back to asking the caller for a workspace id.
func (c *Configurator) ensureSharedWorkspace(ctx context.Context) {
	if c.secrets == nil {
		c.logger.Warn("cannot settle the affine shared workspace: no secrets provider")
		return
	}
	password, err := c.secrets.GenerateAppAdminPassword(appName)
	if err != nil {
		c.logger.Warn("cannot settle the affine shared workspace: no owner password", "err", err)
		return
	}
	if err := c.api.signIn(ctx, c.adminEmail, password); err != nil {
		c.logger.Warn("affine shared workspace: owner sign-in failed", "err", err)
		return
	}

	workspaceID, err := c.ensureWorkspace(ctx)
	if err != nil {
		c.logger.Warn("affine shared workspace: could not settle a workspace", "err", err)
		return
	}
	if err := c.secrets.SetAppContractValue(appName, "appApi", "workspaceId", workspaceID); err != nil {
		c.logger.Warn("affine appApi: could not publish the workspace id", "err", err)
		return
	}
	c.logger.Info("settled the affine shared workspace", "workspace", workspaceID)
}

// ensureWorkspace settles which workspace Bloud works in for the AI profile and
// any appApi companion.
//
// The workspace Bloud already published wins as long as it still exists, so a
// workspace the operator creates later cannot silently move the wiring out from
// under a running companion. Failing that, the first existing workspace is
// adopted, and an instance with no workspace at all gets one created: a purely
// client-side workspace (AFFiNE's onboarding) is invisible to this GraphQL API,
// so Bloud must create the server workspace itself to have anything to wire the
// BYOK profile against.
func (c *Configurator) ensureWorkspace(ctx context.Context) (string, error) {
	ids, err := c.api.listWorkspaces(ctx)
	if err != nil {
		return "", err
	}
	id := c.selectWorkspace(ids)
	if id != "" {
		if id != c.secrets.GetAppContractValue(appName, "appApi", "workspaceId") {
			c.logger.Info("adopting an existing affine workspace", "workspace", id)
		}
		return id, nil
	}
	id, err = c.api.createWorkspace(ctx, workspaceInitDoc)
	if err != nil {
		return "", err
	}
	c.logger.Info("created the affine workspace", "workspace", id)
	return id, nil
}

// selectWorkspace picks the workspace Bloud already works in: the one behind
// the published appApi scope if it still exists, otherwise the first AFFiNE
// reports. Empty when the instance has none. It never creates a workspace,
// because the teardown path must not create one in order to delete a profile
// from it.
func (c *Configurator) selectWorkspace(ids []string) string {
	published := c.secrets.GetAppContractValue(appName, "appApi", "workspaceId")
	for _, id := range ids {
		if id == published {
			return id
		}
	}
	if len(ids) > 0 {
		return ids[0]
	}
	return ""
}

// --- Inference (BYOK endpoint) ---

// byokProfileName labels the profile Bloud owns in AFFiNE's BYOK list. It is
// the identity key for reconciliation: a profile with this name is Bloud's to
// replace or remove, and any other profile is left alone.
const byokProfileName = "Bloud"

// byokDescription is required to be present explicitly on create and replace
// (AFFiNE rejects an input that omits the key). It is what the BYOK list shows
// beside the name.
const byokDescription = "Bloud inference endpoint"

// byokStateFileName is Bloud's own record of what it last wrote into AFFiNE.
// AFFiNE never returns the stored credential, so this is the only way to tell
// a stale gateway key from a current one without rewriting the profile every
// pass. It lives at the app data root, not under config/, so it is not mounted
// into the container.
const byokStateFileName = "bloud-inference.json"

// byokState is the persisted reconciliation state, one record per workspace:
// the profile Bloud owns there and a fingerprint of the credential, endpoint,
// and model it last wrote. Keyed by workspace id because the profile is
// per-workspace and the operator may own several.
type byokState struct {
	Profiles map[string]byokWorkspaceState `json:"profiles"`
}

type byokWorkspaceState struct {
	ProfileID   string `json:"profileId"`
	Fingerprint string `json:"fingerprint"`
}

// inferenceBinding pulls the resolved inference binding out of the app state.
// The bool reports whether the contract is bound at all, which is what separates
// "remove Bloud's endpoint" (unbound) from "the binding is not ready yet"
// (bound but incomplete).
func inferenceBinding(state *configurator.AppState) (configurator.InferenceBinding, bool) {
	if state == nil || len(state.Integrations.Inference) == 0 {
		return configurator.InferenceBinding{}, false
	}
	return state.Integrations.Inference[0], true
}

// ensureInferenceProvider points AFFiNE's built-in AI at Bloud's resolved
// inference endpoint by registering it as a per-workspace BYOK profile.
//
// AFFiNE's AI is "bring your own key" in shape; Bloud makes it "bring your own
// endpoint" by holding the credential behind its gateway, so the operator never
// handles a real provider secret. The profile is workspace-scoped and stored in
// AFFiNE's database, which is why this runs in PostStart through AFFiNE's API
// rather than being written into config.json (config.json only opens the
// custom-endpoint policy; see renderConfigFile).
//
// Idempotent: when the profile already matches what Bloud last wrote, nothing
// is sent. A credential-only change rotates the credential; an endpoint or
// model change replaces the profile; a profile deleted in the AFFiNE UI is
// recreated. Failures are logged and swallowed, exactly like the MCP
// credential: a knowledge base that serves its users fine must not land in
// ERROR because AI wiring failed, and the next pass retries.
func (c *Configurator) ensureInferenceProvider(ctx context.Context, state *configurator.AppState) {
	binding, declared := inferenceBinding(state)
	if !declared {
		c.removeInferenceProvider(ctx, state)
		return
	}
	// A bound but incomplete binding is "not ready", not "unbind": an empty
	// endpoint or default model would be stored as a profile AFFiNE cannot use.
	// A missing credential is NOT "not ready": this instance's gateway may be
	// keyless, and the profile still has to be registered (see byokCredential).
	if binding.Endpoint == "" || binding.DefaultModel == "" {
		c.logger.Info("affine AI: inference binding is not ready, wiring nothing",
			"endpoint", binding.Endpoint, "model", binding.DefaultModel)
		return
	}
	if c.secrets == nil {
		c.logger.Warn("cannot wire affine AI: no secrets provider")
		return
	}
	password, err := c.secrets.GenerateAppAdminPassword(appName)
	if err != nil {
		c.logger.Warn("cannot wire affine AI: no owner password", "err", err)
		return
	}
	if err := c.api.signIn(ctx, c.adminEmail, password); err != nil {
		c.logger.Warn("affine AI: owner sign-in failed, wiring nothing", "err", err)
		return
	}
	ids, err := c.api.listWorkspaces(ctx)
	if err != nil {
		c.logger.Warn("affine AI: could not list workspaces", "err", err)
		return
	}
	if len(ids) == 0 {
		c.logger.Info("affine AI: no workspaces yet, wiring nothing")
		return
	}

	stored := c.readByokState(state)
	if stored.Profiles == nil {
		stored.Profiles = map[string]byokWorkspaceState{}
	}
	for _, workspaceID := range ids {
		c.ensureWorkspaceInference(ctx, workspaceID, binding, &stored)
	}
	// Drop records for workspaces that no longer exist so the state file does
	// not accumulate dead profile ids.
	keep := make(map[string]bool, len(ids))
	for _, id := range ids {
		keep[id] = true
	}
	for id := range stored.Profiles {
		if !keep[id] {
			delete(stored.Profiles, id)
		}
	}
	c.writeByokState(state, stored)
}

// ensureWorkspaceInference makes one workspace's BYOK settings point at Bloud's
// endpoint. It is the single-workspace half of ensureInferenceProvider: the
// caller decides which workspaces to visit (now: every workspace the operator's
// account belongs to), this function makes each one match. The recorded state is
// stored under the workspace id in the shared map so a profile id is never
// mistaken for another workspace's.
func (c *Configurator) ensureWorkspaceInference(ctx context.Context, workspaceID string, binding configurator.InferenceBinding, stored *byokState) {
	settings, err := c.api.byokSettings(ctx, workspaceID)
	if err != nil {
		c.logger.Warn("affine AI: could not read BYOK settings", "workspace", workspaceID, "err", err)
		return
	}
	// The mode is driven by config.json, which PreStart writes and which forces
	// a container recreate before PostStart, so a disabled mode here means the
	// config did not take effect rather than a code defect.
	if settings.Policy.CustomEndpointMode != "enabled" {
		c.logger.Warn("affine AI: custom endpoints are disabled on the server",
			"workspace", workspaceID, "mode", settings.Policy.CustomEndpointMode)
		return
	}

	existing := findBloudProfile(settings.Profiles)
	fingerprint := byokFingerprint(workspaceID, binding)
	ws := stored.Profiles[workspaceID]
	if existing != nil && ws.ProfileID == existing.ProfileID && ws.Fingerprint == fingerprint {
		return
	}

	if existing == nil {
		profileID, err := c.api.createByokProfile(ctx, workspaceID, byokCredential(binding), byokProfileName, byokDescription, binding)
		if err != nil {
			c.logger.Warn("affine AI: could not register the endpoint", "workspace", workspaceID, "err", err)
			return
		}
		stored.Profiles[workspaceID] = byokWorkspaceState{ProfileID: profileID, Fingerprint: fingerprint}
		c.logger.Info("registered affine AI endpoint", "workspace", workspaceID, "profile", profileID)
		return
	}

	// The definition is unchanged, so only the credential can differ. Rotating
	// leaves the definition and its revision untouched; a replace would needlessly
	// bump the revision. A missing state record also lands here, which converges
	// in one pass because the record is written below.
	if sameByokDefinition(existing, binding) {
		if err := c.api.rotateByokCredential(ctx, workspaceID, existing.ProfileID, byokCredential(binding), existing.Revision); err != nil {
			c.logger.Warn("affine AI: could not rotate the credential", "workspace", workspaceID, "err", err)
			return
		}
		stored.Profiles[workspaceID] = byokWorkspaceState{ProfileID: existing.ProfileID, Fingerprint: fingerprint}
		c.logger.Info("rotated the affine AI credential", "workspace", workspaceID, "profile", existing.ProfileID)
		return
	}

	if err := c.api.replaceByokProfile(ctx, workspaceID, existing.ProfileID, byokCredential(binding), byokProfileName, byokDescription, existing.Revision, binding); err != nil {
		c.logger.Warn("affine AI: could not update the endpoint", "workspace", workspaceID, "err", err)
		return
	}
	stored.Profiles[workspaceID] = byokWorkspaceState{ProfileID: existing.ProfileID, Fingerprint: fingerprint}
	c.logger.Info("updated affine AI endpoint", "workspace", workspaceID, "profile", existing.ProfileID)
}

// removeInferenceProvider deletes the profile Bloud owns when the app no longer
// declares a bound inference contract (the gateway was uninstalled or the
// setting cleared), so AFFiNE stops dialing an endpoint that is gone. It acts
// only on the profile id Bloud recorded, so a profile the operator registered by
// hand is never touched.
func (c *Configurator) removeInferenceProvider(ctx context.Context, state *configurator.AppState) {
	stored := c.readByokState(state)
	if len(stored.Profiles) == 0 || c.secrets == nil {
		return
	}
	password, err := c.secrets.GenerateAppAdminPassword(appName)
	if err != nil {
		c.logger.Warn("affine AI: cannot remove the endpoint: no owner password", "err", err)
		return
	}
	if err := c.api.signIn(ctx, c.adminEmail, password); err != nil {
		c.logger.Warn("affine AI: owner sign-in failed, removing nothing", "err", err)
		return
	}
	ids, err := c.api.listWorkspaces(ctx)
	if err != nil {
		return
	}
	for _, workspaceID := range ids {
		ws, ok := stored.Profiles[workspaceID]
		if !ok || ws.ProfileID == "" {
			continue
		}
		if err := c.api.deleteByokProfile(ctx, workspaceID, ws.ProfileID); err != nil {
			c.logger.Warn("affine AI: could not remove the endpoint", "workspace", workspaceID, "err", err)
			continue
		}
		c.logger.Info("removed affine AI endpoint", "workspace", workspaceID)
	}
	c.removeByokState(state)
}

// findBloudProfile returns the profile Bloud owns, or nil. Provider is checked
// alongside the name so an operator profile that happens to be named "Bloud"
// but points elsewhere is never adopted.
func findBloudProfile(profiles []byokProfile) *byokProfile {
	for i := range profiles {
		if profiles[i].Provider == byokProviderOpenAI && profiles[i].Name == byokProfileName {
			return &profiles[i]
		}
	}
	return nil
}

// sameByokDefinition reports whether AFFiNE's stored profile already has the
// endpoint, dialect, and model Bloud wants. A disabled profile counts as
// different so it is re-enabled.
func sameByokDefinition(p *byokProfile, b configurator.InferenceBinding) bool {
	if !p.Enabled || p.Definition.Endpoint.Kind != byokEndpointOpenAICompatible {
		return false
	}
	if p.Definition.Endpoint.URL == nil || *p.Definition.Endpoint.URL != b.Endpoint {
		return false
	}
	if p.Definition.Endpoint.Dialect == nil || *p.Definition.Endpoint.Dialect != byokDialectChatCompletions {
		return false
	}
	if len(p.Definition.Models) != 1 {
		return false
	}
	m := p.Definition.Models[0]
	return m.ModelID == b.DefaultModel && m.Enabled
}

// byokKeylessCredential fills the credential slot when the resolved upstream
// needs no key. AFFiNE's BYOK input requires a credential string and its
// OpenAI-compatible client sends it as a bearer, so an empty value risks a
// client-construction failure; a keyless gateway ignores the header, so the
// value is inert. An operator who sets a real key on the instance upstream gets
// that key instead (see byokCredential).
const byokKeylessCredential = "bloud"

// byokCredential is the credential Bloud stores in AFFiNE for this binding: the
// instance's real key when there is one, otherwise the keyless placeholder.
func byokCredential(b configurator.InferenceBinding) string {
	if b.APIKey != "" {
		return b.APIKey
	}
	return byokKeylessCredential
}

// byokFingerprint is a stable hash of everything Bloud controls about the
// profile except its identity. The credential is included because AFFiNE does
// not return it, so this hash is the only signal that a rotation is due; the
// full definition is included so a capability change (e.g. adding tool_calling)
// also re-writes the profile.
func byokFingerprint(workspaceID string, b configurator.InferenceBinding) string {
	def, _ := json.Marshal(byokDefinition(b))
	sum := sha256.Sum256([]byte(strings.Join([]string{
		workspaceID, byokProviderOpenAI, byokProfileName, b.Endpoint,
		byokDialectChatCompletions, b.DefaultModel, byokCredential(b), string(def),
	}, "\x00")))
	return hex.EncodeToString(sum[:])
}

func (c *Configurator) byokStatePath(state *configurator.AppState) string {
	return filepath.Join(state.DataPath, byokStateFileName)
}

func (c *Configurator) readByokState(state *configurator.AppState) byokState {
	raw, err := os.ReadFile(c.byokStatePath(state))
	if err != nil {
		return byokState{}
	}
	var s byokState
	if err := json.Unmarshal(raw, &s); err != nil {
		return byokState{}
	}
	return s
}

func (c *Configurator) writeByokState(state *configurator.AppState, s byokState) {
	raw, err := json.Marshal(s)
	if err != nil {
		return
	}
	if _, err := managedfile.Write(c.byokStatePath(state), append(raw, '\n'), managedfile.ModeHostOnly); err != nil {
		c.logger.Warn("affine AI: could not persist reconciliation state", "err", err)
	}
}

func (c *Configurator) removeByokState(state *configurator.AppState) {
	if err := os.Remove(c.byokStatePath(state)); err != nil && !os.IsNotExist(err) {
		c.logger.Warn("affine AI: could not clear reconciliation state", "err", err)
	}
}

// --- Config file ---

// renderConfigFile renders the AFFiNE config.json. Only keys that override
// defaults are set; AFFiNE merges the file over its built-in defaults.
func renderConfigFile(externalURL string, oidc *configurator.OIDCOutput) (string, error) {
	cfg := map[string]any{
		"server": map[string]any{
			"externalUrl": externalURL,
		},
		// AFFiNE's first-open flow creates a local "Demo Workspace" (nanoid)
		// when this flag is on, and the operator lands in that demo instead of
		// the server workspace Bloud created and wired with the AI endpoint. A
		// local workspace is invisible to Bloud's GraphQL API, so the BYOK
		// profile and the AI chat would live in different workspaces and every
		// chat would fail with `no_compatible_target`. Disabling the guest demo
		// makes the operator's first workspace the server one Bloud owns.
		"flags": map[string]any{
			"allowGuestDemoWorkspace": false,
		},
		// The invite quota is the one thing standing between Bloud and adding its
		// own users to its own workspace, and on self-host it is set to zero: the
		// admission check answers `limit: 0, reason: 'quota_subject'` and every
		// `inviteMembers` call is a 429. The guard exists to stop anonymous
		// signups spamming invites to strangers on AFFiNE's hosted infrastructure.
		// Neither applies here: the inviter is Bloud's own bootstrap admin, the
		// invitees are the accounts the operator created in Bloud's identity
		// provider, and the server is a home box with no mail transport. Shadow
		// mode keeps the accounting and drops the rejection, which is the whole
		// point of the flag rather than a bypass of it.
		"auth": map[string]any{
			"inviteQuotaShadowMode": true,
		},
		// The MCP server lives under AFFiNE's copilot module and the flag
		// defaults off, so without this every credential mint and every MCP
		// request answers "Copilot is disabled."
		//
		// The byok block is the policy half of the inference wiring: AFFiNE
		// gates an OpenAI-compatible endpoint behind an explicit server
		// opt-in, and Bloud's gateway is one. `allowCustomEndpoint` makes the
		// custom-endpoint mode "enabled" (the Rust policy returns
		// "disabled" on self-host without it), and `allowPrivateEndpoint`
		// admits a container-network address, which `apps-litellm` /
		// `apps-ollama` are. A public endpoint needs neither, but the private
		// case is the one Bloud ships, so the flag is on. The trade-off is
		// AFFiNE's own warning: every workspace admin may then point AFFiNE
		// at a private-network service. Acceptable for a single-tenant home
		// server, and it is what makes the endpoint reachable at all.
		"copilot": map[string]any{
			"enabled": true,
			"byok": map[string]any{
				"enabled":              true,
				"allowCustomEndpoint":  true,
				"allowPrivateEndpoint": true,
			},
		},
	}
	if oidc != nil {
		cfg["oauth"] = map[string]any{
			"providers": map[string]any{
				"oidc": map[string]any{
					"clientId":            oidc.ClientID,
					"clientSecret":        oidc.ClientSecret,
					"issuer":              oidc.IssuerURL,
					"allowPrivateNetwork": true,
				},
			},
		}
	}
	// json.Marshal sorts map keys alphabetically, so the rendering is
	// deterministic: an unchanged config never churns the file across
	// reconciliation cycles.
	out, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return "", fmt.Errorf("rendering config file: %w", err)
	}
	return string(out) + "\n", nil
}
