package affine

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"codeberg.org/d-buckner/bloud-v3/services/host-agent/pkg/configurator"
)

// Configurator handles AFFiNE configuration
type Configurator struct {
	port    int
	dataDir string
}

// NewConfigurator creates a new AFFiNE configurator
func NewConfigurator(port int, dataDir string) *Configurator {
	return &Configurator{
		port:    port,
		dataDir: dataDir,
	}
}

// Name returns the app name
func (c *Configurator) Name() string {
	return "affine"
}

// PreStart ensures the affine.js config file exists for the volume mount.
// OIDC settings are handled via environment variables written by writeSSOEnvVars
// at prestart time, so affine.js no longer needs OIDC configuration.
func (c *Configurator) PreStart(ctx context.Context, state *configurator.AppState) error {
	configDir := filepath.Join(c.dataDir, "affine")
	configPath := filepath.Join(configDir, "affine.js")

	// Ensure config directory exists
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return fmt.Errorf("failed to create config dir: %w", err)
	}

	// Create config file so volume mount doesn't fail.
	// OIDC is configured entirely via env vars (OAUTH_OIDC_ISSUER, etc.)
	if err := os.WriteFile(configPath, []byte("// Auto-generated by Bloud configurator\n"), 0644); err != nil {
		return fmt.Errorf("failed to write affine.js config: %w", err)
	}

	return nil
}

// HealthCheck waits for AFFiNE to be ready
func (c *Configurator) HealthCheck(ctx context.Context) error {
	url := fmt.Sprintf("http://localhost:%d/", c.port)
	return configurator.WaitForHTTP(ctx, url, configurator.DefaultHealthCheckTimeout)
}

// PostStart handles post-startup configuration
func (c *Configurator) PostStart(ctx context.Context, state *configurator.AppState) error {
	// No post-start configuration needed for AFFiNE
	return nil
}
