package traefikgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"codeberg.org/d-buckner/bloud/services/host-agent/internal/catalog"
)

// Generator generates Traefik dynamic configuration for installed apps
type Generator struct {
	configPath       string // Path to apps-routes.yml
	authentikEnabled bool   // Whether Authentik is installed (for SSO middlewares)
}

// NewGenerator creates a Traefik config generator
func NewGenerator(configPath string) *Generator {
	return &Generator{
		configPath: configPath,
	}
}

// SetAuthentikEnabled updates the Authentik status for SSO middleware generation
func (g *Generator) SetAuthentikEnabled(enabled bool) {
	g.authentikEnabled = enabled
}

// Generate creates Traefik routes for the given installed apps.
// Backward-compatible: delegates to GenerateAll with no remote apps or tailnet.
func (g *Generator) Generate(apps []*catalog.App) error {
	return g.GenerateAll(apps, nil, "")
}

// GenerateAll creates Traefik routes for local apps, remote (shared) apps,
// and tailnet-specific routes when tailnetDomain is non-empty.
func (g *Generator) GenerateAll(apps []*catalog.App, remoteApps []RemoteAppRoute, tailnetDomain string) error {
	config := g.generateConfig(apps, remoteApps, tailnetDomain)

	// Ensure parent directory exists
	dir := filepath.Dir(g.configPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Write config atomically (write temp file, then rename)
	tempPath := g.configPath + ".tmp"
	if err := os.WriteFile(tempPath, []byte(config), 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	if err := os.Rename(tempPath, g.configPath); err != nil {
		os.Remove(tempPath)
		return fmt.Errorf("failed to update config: %w", err)
	}

	return nil
}

// generateConfig creates the YAML configuration for Traefik
func (g *Generator) generateConfig(apps []*catalog.App, remoteApps []RemoteAppRoute, tailnetDomain string) string {
	var b strings.Builder

	b.WriteString("# Generated by Bloud - DO NOT EDIT MANUALLY\n")
	b.WriteString("# This file is managed by the Bloud host agent\n")
	b.WriteString("# Traefik watches this file for changes\n\n")

	// Filter to routable apps: non-system apps with ports
	var routableApps []*catalog.App
	for _, app := range apps {
		if !app.IsSystem && app.Port > 0 {
			routableApps = append(routableApps, app)
		}
	}

	if len(routableApps) == 0 && len(remoteApps) == 0 {
		b.WriteString("# No routable apps installed\n")
		return b.String()
	}

	// Sort apps for deterministic output
	sort.Slice(routableApps, func(i, j int) bool {
		return routableApps[i].CatalogID < routableApps[j].CatalogID
	})
	sort.Slice(remoteApps, func(i, j int) bool {
		return remoteApps[i].ID < remoteApps[j].ID
	})

	// Generate routers section
	b.WriteString("http:\n")
	b.WriteString("  routers:\n")
	for _, app := range routableApps {
		g.writeRouter(&b, app, g.authentikEnabled)
		if app.SSO.Strategy == "forward-auth" && g.authentikEnabled {
			// Forward-auth apps need a second, higher-priority router that passes
			// /outpost.goauthentik.io/ requests directly to Authentik. Without this,
			// the OAuth callback (code exchange) gets intercepted by the forward-auth
			// middleware and the embedded outpost returns 400.
			g.writeOutpostRouter(&b, app)
			// Native-client API paths bypass forward-auth so apps like Navidrome can
			// serve Subsonic clients using their own credential scheme.
			for _, path := range app.SSO.BypassPaths {
				g.writeBypassRouter(&b, app, path)
			}
		}
	}
	for _, ra := range remoteApps {
		g.writeRemoteRouter(&b, ra)
	}

	// Tailnet-specific routers: higher-priority routes that use the standalone
	// proxy outpost for forward-auth, so remote users get redirected to the
	// tailnet URL for login instead of localhost.
	hasTailnetRoutes := false
	if tailnetDomain != "" && g.authentikEnabled {
		for _, app := range routableApps {
			if app.SSO.Strategy == "forward-auth" {
				g.writeTailnetRouter(&b, app, tailnetDomain)
				g.writeTailnetOutpostRouter(&b, app, tailnetDomain)
				hasTailnetRoutes = true
			}
		}
		// Gateway domain routes: Authentik login page + outpost callback.
		g.writeTailnetGatewayRouters(&b, tailnetDomain)
	}

	// Generate middlewares section (only if any app needs one)
	hasMiddlewares := false
	for _, app := range routableApps {
		if g.appNeedsMiddleware(app) {
			hasMiddlewares = true
			break
		}
	}
	if hasMiddlewares || hasTailnetRoutes {
		b.WriteString("\n  middlewares:\n")
		for _, app := range routableApps {
			g.writeMiddleware(&b, app)
		}
		if hasTailnetRoutes {
			g.writeTailnetMiddleware(&b)
		}
	}

	// Generate services section
	b.WriteString("\n  services:\n")
	for _, app := range routableApps {
		g.writeService(&b, app)
	}
	for _, ra := range remoteApps {
		g.writeRemoteService(&b, ra)
	}

	// Add the shared authentik-outpost service if any forward-auth apps are installed
	hasForwardAuth := false
	for _, app := range routableApps {
		if app.SSO.Strategy == "forward-auth" && g.authentikEnabled {
			hasForwardAuth = true
			break
		}
	}
	if hasForwardAuth {
		b.WriteString("    authentik-outpost:\n")
		b.WriteString("      loadBalancer:\n")
		b.WriteString("        servers:\n")
		b.WriteString("          - url: \"http://localhost:9001\"\n")
	}

	// Tailnet services: standalone proxy outpost + Authentik web UI.
	if hasTailnetRoutes {
		g.writeTailnetServices(&b)
	}

	return b.String()
}

// appNeedsMiddleware returns true if the app requires any middleware definitions
func (g *Generator) appNeedsMiddleware(app *catalog.App) bool {
	if app.SSO.Strategy == "forward-auth" && g.authentikEnabled {
		return true
	}
	if app.Routing != nil && len(app.Routing.Headers) > 0 {
		return true
	}
	return false
}

// writeRouter writes the router configuration for an app.
// Uses HostRegexp for domain-agnostic subdomain matching: matches jellyfin.localhost,
// jellyfin.bloud.co, jellyfin.<anything> — any host starting with the app's subdomain.
func (g *Generator) writeRouter(b *strings.Builder, app *catalog.App, authentikEnabled bool) {
	b.WriteString(fmt.Sprintf("    %s:\n", app.CatalogID))
	b.WriteString(fmt.Sprintf("      rule: \"HostRegexp(`^%s\\\\.`)\"\n", app.CatalogID))
	b.WriteString("      priority: 200\n")

	// Build middleware list
	var middlewares []string

	// Forward auth middleware for apps using forward-auth SSO strategy
	if app.SSO.Strategy == "forward-auth" && authentikEnabled {
		middlewares = append(middlewares, fmt.Sprintf("%s-forwardauth", app.CatalogID))
	}

	// Add custom headers middleware if app has routing headers
	if app.Routing != nil && len(app.Routing.Headers) > 0 {
		middlewares = append(middlewares, fmt.Sprintf("%s-headers", app.CatalogID))
	}

	if len(middlewares) > 0 {
		b.WriteString("      middlewares:\n")
		for _, mw := range middlewares {
			b.WriteString(fmt.Sprintf("        - %s\n", mw))
		}
	}

	b.WriteString(fmt.Sprintf("      service: %s\n", app.CatalogID))
}

// writeMiddleware writes the middleware configuration for an app
func (g *Generator) writeMiddleware(b *strings.Builder, app *catalog.App) {
	// ForwardAuth middleware for apps using forward-auth SSO strategy
	if app.SSO.Strategy == "forward-auth" && g.authentikEnabled {
		b.WriteString(fmt.Sprintf("    %s-forwardauth:\n", app.CatalogID))
		b.WriteString("      forwardAuth:\n")
		b.WriteString("        address: \"http://localhost:9001/outpost.goauthentik.io/auth/traefik\"\n")
		b.WriteString("        trustForwardHeader: true\n")
		b.WriteString("        authResponseHeaders:\n")
		b.WriteString("          - X-authentik-username\n")
		b.WriteString("          - X-authentik-groups\n")
		b.WriteString("          - X-authentik-email\n")
		b.WriteString("          - X-authentik-name\n")
		b.WriteString("          - X-authentik-uid\n")
	}

	// Custom headers middleware (only if app has routing headers)
	if app.Routing != nil && len(app.Routing.Headers) > 0 {
		g.writeHeadersMiddleware(b, fmt.Sprintf("%s-headers", app.CatalogID), app.Routing.Headers)
	}
}

// writeHeadersMiddleware writes a headers middleware with the given name and headers
func (g *Generator) writeHeadersMiddleware(b *strings.Builder, name string, headers map[string]string) {
	b.WriteString(fmt.Sprintf("    %s:\n", name))
	b.WriteString("      headers:\n")
	b.WriteString("        customResponseHeaders:\n")

	// Sort headers for deterministic output
	var headerNames []string
	for headerName := range headers {
		headerNames = append(headerNames, headerName)
	}
	sort.Strings(headerNames)

	for _, headerName := range headerNames {
		b.WriteString(fmt.Sprintf("          %s: \"%s\"\n", headerName, headers[headerName]))
	}
}

// writeBypassRouter writes a high-priority router that routes a specific path prefix
// directly to the app service, bypassing forward-auth. Used for native-client API
// paths (e.g. /rest/ for Subsonic clients) that carry their own credentials.
func (g *Generator) writeBypassRouter(b *strings.Builder, app *catalog.App, path string) {
	// Derive a safe router name from the path: strip slashes, replace / with -.
	sanitized := strings.Trim(path, "/")
	sanitized = strings.ReplaceAll(sanitized, "/", "-")
	b.WriteString(fmt.Sprintf("    %s-bypass-%s:\n", app.CatalogID, sanitized))
	b.WriteString(fmt.Sprintf("      rule: \"HostRegexp(`^%s\\\\.`) && PathPrefix(`%s`)\"\n", app.CatalogID, path))
	b.WriteString(fmt.Sprintf("      service: %s\n", app.CatalogID))
	b.WriteString("      priority: 300\n")
}

// writeOutpostRouter writes a high-priority router that passes /outpost.goauthentik.io/
// requests for a forward-auth app directly to the Authentik embedded outpost,
// bypassing the forward-auth middleware so the OAuth callback can complete.
func (g *Generator) writeOutpostRouter(b *strings.Builder, app *catalog.App) {
	b.WriteString(fmt.Sprintf("    %s-outpost:\n", app.CatalogID))
	b.WriteString(fmt.Sprintf("      rule: \"HostRegexp(`^%s\\\\.`) && PathPrefix(`/outpost.goauthentik.io/`)\"\n", app.CatalogID))
	b.WriteString("      service: authentik-outpost\n")
	b.WriteString("      priority: 300\n")
}

// writeService writes the service configuration for an app
func (g *Generator) writeService(b *strings.Builder, app *catalog.App) {
	b.WriteString(fmt.Sprintf("    %s:\n", app.CatalogID))
	b.WriteString("      loadBalancer:\n")
	b.WriteString("        servers:\n")
	b.WriteString(fmt.Sprintf("          - url: \"http://localhost:%d\"\n", app.Port))
}

// writeRemoteRouter writes the router configuration for a remote (shared) app.
func (g *Generator) writeRemoteRouter(b *strings.Builder, ra RemoteAppRoute) {
	routerName := "shared-" + ra.ID

	b.WriteString(fmt.Sprintf("    %s:\n", routerName))
	b.WriteString(fmt.Sprintf("      rule: \"HostRegexp(`^%s\\\\.`)\"\n", ra.ID))
	b.WriteString("      priority: 200\n")
	b.WriteString(fmt.Sprintf("      service: %s\n", routerName))
}

// writeRemoteService writes the service configuration for a remote (shared) app.
func (g *Generator) writeRemoteService(b *strings.Builder, ra RemoteAppRoute) {
	serviceName := "shared-" + ra.ID

	b.WriteString(fmt.Sprintf("    %s:\n", serviceName))
	b.WriteString("      loadBalancer:\n")
	b.WriteString("        servers:\n")
	b.WriteString(fmt.Sprintf("          - url: \"%s\"\n", ra.ProxyURL))
}

// writeTailnetRouter writes a tailnet-specific router for a forward-auth app.
// Higher priority (250) than the local router (200), so requests matching the
// tailnet domain use the standalone outpost for auth instead of the embedded one.
func (g *Generator) writeTailnetRouter(b *strings.Builder, app *catalog.App, tailnetDomain string) {
	b.WriteString(fmt.Sprintf("    %s-tailnet:\n", app.CatalogID))
	b.WriteString(fmt.Sprintf("      rule: \"Host(`%s.%s`)\"\n", app.CatalogID, tailnetDomain))
	b.WriteString("      priority: 250\n")
	b.WriteString("      middlewares:\n")
	b.WriteString("        - tailnet-forwardauth\n")
	b.WriteString(fmt.Sprintf("      service: %s\n", app.CatalogID))
}

// writeTailnetOutpostRouter writes a router for /outpost.goauthentik.io/ paths
// on tailnet app domains. This ensures the OAuth callback from the standalone
// outpost is routed to the outpost, not to the app.
func (g *Generator) writeTailnetOutpostRouter(b *strings.Builder, app *catalog.App, tailnetDomain string) {
	b.WriteString(fmt.Sprintf("    %s-tailnet-outpost:\n", app.CatalogID))
	b.WriteString(fmt.Sprintf("      rule: \"Host(`%s.%s`) && PathPrefix(`/outpost.goauthentik.io/`)\"\n", app.CatalogID, tailnetDomain))
	b.WriteString("      priority: 300\n")
	b.WriteString("      service: tailnet-outpost\n")
}

// writeTailnetGatewayRouters writes routers for the gateway domain (bloud.{tailnetDomain}).
// Two routers: one for the outpost callback (priority 300) and one for the Authentik
// login page (priority 200).
func (g *Generator) writeTailnetGatewayRouters(b *strings.Builder, tailnetDomain string) {
	// Outpost callback router — must be higher priority to intercept /outpost.goauthentik.io/
	b.WriteString("    tailnet-gateway-outpost:\n")
	b.WriteString(fmt.Sprintf("      rule: \"Host(`bloud.%s`) && PathPrefix(`/outpost.goauthentik.io/`)\"\n", tailnetDomain))
	b.WriteString("      priority: 300\n")
	b.WriteString("      service: tailnet-outpost\n")

	// Authentik login page — serves the OAuth authorization + login UI
	b.WriteString("    tailnet-gateway-authentik:\n")
	b.WriteString(fmt.Sprintf("      rule: \"Host(`bloud.%s`)\"\n", tailnetDomain))
	b.WriteString("      priority: 200\n")
	b.WriteString("      service: authentik-web\n")
}

// writeTailnetMiddleware writes the forward-auth middleware for tailnet access.
// Points to the standalone proxy outpost on port 9002 instead of the embedded
// outpost on port 9001.
func (g *Generator) writeTailnetMiddleware(b *strings.Builder) {
	b.WriteString("    tailnet-forwardauth:\n")
	b.WriteString("      forwardAuth:\n")
	b.WriteString("        address: \"http://localhost:9002/outpost.goauthentik.io/auth/traefik\"\n")
	b.WriteString("        trustForwardHeader: true\n")
	b.WriteString("        authResponseHeaders:\n")
	b.WriteString("          - X-authentik-username\n")
	b.WriteString("          - X-authentik-groups\n")
	b.WriteString("          - X-authentik-email\n")
	b.WriteString("          - X-authentik-name\n")
	b.WriteString("          - X-authentik-uid\n")
}

// writeTailnetServices writes the service definitions for tailnet routing:
// the standalone proxy outpost and the Authentik web UI.
func (g *Generator) writeTailnetServices(b *strings.Builder) {
	b.WriteString("    tailnet-outpost:\n")
	b.WriteString("      loadBalancer:\n")
	b.WriteString("        servers:\n")
	b.WriteString("          - url: \"http://localhost:9002\"\n")
	b.WriteString("    authentik-web:\n")
	b.WriteString("      loadBalancer:\n")
	b.WriteString("        servers:\n")
	b.WriteString("          - url: \"http://localhost:9001\"\n")
}

// Preview generates a preview of what the config will look like
func (g *Generator) Preview(apps []*catalog.App) string {
	return g.generateConfig(apps, nil, "")
}
