package traefikgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"codeberg.org/d-buckner/bloud-v3/services/host-agent/internal/catalog"
)

// Generator generates Traefik dynamic configuration for installed apps
type Generator struct {
	configPath       string // Path to apps-routes.yml
	baseDomain       string // Base domain for subdomain routing (e.g., "localhost")
	authentikEnabled bool   // Whether Authentik is installed (for SSO middlewares)
}

// NewGenerator creates a Traefik config generator
func NewGenerator(configPath, baseDomain string) *Generator {
	return &Generator{
		configPath: configPath,
		baseDomain: baseDomain,
	}
}

// SetAuthentikEnabled updates the Authentik status for SSO middleware generation
func (g *Generator) SetAuthentikEnabled(enabled bool) {
	g.authentikEnabled = enabled
}

// Generate creates Traefik routes for the given installed apps
func (g *Generator) Generate(apps []*catalog.App) error {
	config := g.generateConfig(apps)

	// Ensure parent directory exists
	dir := filepath.Dir(g.configPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	// Write config atomically (write temp file, then rename)
	tempPath := g.configPath + ".tmp"
	if err := os.WriteFile(tempPath, []byte(config), 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	if err := os.Rename(tempPath, g.configPath); err != nil {
		os.Remove(tempPath)
		return fmt.Errorf("failed to update config: %w", err)
	}

	return nil
}

// generateConfig creates the YAML configuration for Traefik
func (g *Generator) generateConfig(apps []*catalog.App) string {
	var b strings.Builder

	b.WriteString("# Generated by Bloud - DO NOT EDIT MANUALLY\n")
	b.WriteString("# This file is managed by the Bloud host agent\n")
	b.WriteString("# Traefik watches this file for changes\n\n")

	// Filter to routable apps: non-system apps with ports
	var routableApps []*catalog.App
	for _, app := range apps {
		if !app.IsSystem && app.Port > 0 {
			routableApps = append(routableApps, app)
		}
	}

	if len(routableApps) == 0 {
		b.WriteString("# No routable apps installed\n")
		return b.String()
	}

	// Sort apps for deterministic output
	sort.Slice(routableApps, func(i, j int) bool {
		return routableApps[i].Name < routableApps[j].Name
	})

	// Generate routers section
	b.WriteString("http:\n")
	b.WriteString("  routers:\n")
	for _, app := range routableApps {
		g.writeRouter(&b, app, g.authentikEnabled)
		// Forward-auth apps need a second, higher-priority router that passes
		// /outpost.goauthentik.io/ requests directly to Authentik. Without this,
		// the OAuth callback (code exchange) gets intercepted by the forward-auth
		// middleware and the embedded outpost returns 400.
		if app.SSO.Strategy == "forward-auth" && g.authentikEnabled {
			g.writeOutpostRouter(&b, app)
		}
	}

	// Generate middlewares section (only if any app needs one)
	hasMiddlewares := false
	for _, app := range routableApps {
		if g.appNeedsMiddleware(app) {
			hasMiddlewares = true
			break
		}
	}
	if hasMiddlewares {
		b.WriteString("\n  middlewares:\n")
		for _, app := range routableApps {
			g.writeMiddleware(&b, app)
		}
	}

	// Generate services section
	b.WriteString("\n  services:\n")
	for _, app := range routableApps {
		g.writeService(&b, app)
	}

	// Add the shared authentik-outpost service if any forward-auth apps are installed
	hasForwardAuth := false
	for _, app := range routableApps {
		if app.SSO.Strategy == "forward-auth" && g.authentikEnabled {
			hasForwardAuth = true
			break
		}
	}
	if hasForwardAuth {
		b.WriteString("    authentik-outpost:\n")
		b.WriteString("      loadBalancer:\n")
		b.WriteString("        servers:\n")
		b.WriteString("          - url: \"http://localhost:9001\"\n")
	}

	return b.String()
}

// appNeedsMiddleware returns true if the app requires any middleware definitions
func (g *Generator) appNeedsMiddleware(app *catalog.App) bool {
	if app.SSO.Strategy == "forward-auth" && g.authentikEnabled {
		return true
	}
	if app.Routing != nil && len(app.Routing.Headers) > 0 {
		return true
	}
	return false
}

// writeRouter writes the router configuration for an app.
// Uses Host-based subdomain routing: jellyfin.localhost, miniflux.localhost, etc.
func (g *Generator) writeRouter(b *strings.Builder, app *catalog.App, authentikEnabled bool) {
	hostRule := fmt.Sprintf("%s.%s", app.Name, g.baseDomain)

	b.WriteString(fmt.Sprintf("    %s:\n", app.Name))
	b.WriteString(fmt.Sprintf("      rule: \"Host(`%s`)\"\n", hostRule))

	// Build middleware list
	var middlewares []string

	// Forward auth middleware for apps using forward-auth SSO strategy
	if app.SSO.Strategy == "forward-auth" && authentikEnabled {
		middlewares = append(middlewares, fmt.Sprintf("%s-forwardauth", app.Name))
	}

	// Add custom headers middleware if app has routing headers
	if app.Routing != nil && len(app.Routing.Headers) > 0 {
		middlewares = append(middlewares, fmt.Sprintf("%s-headers", app.Name))
	}

	if len(middlewares) > 0 {
		b.WriteString("      middlewares:\n")
		for _, mw := range middlewares {
			b.WriteString(fmt.Sprintf("        - %s\n", mw))
		}
	}

	b.WriteString(fmt.Sprintf("      service: %s\n", app.Name))
}

// writeMiddleware writes the middleware configuration for an app
func (g *Generator) writeMiddleware(b *strings.Builder, app *catalog.App) {
	// ForwardAuth middleware for apps using forward-auth SSO strategy
	if app.SSO.Strategy == "forward-auth" && g.authentikEnabled {
		b.WriteString(fmt.Sprintf("    %s-forwardauth:\n", app.Name))
		b.WriteString("      forwardAuth:\n")
		b.WriteString("        address: \"http://localhost:9001/outpost.goauthentik.io/auth/traefik\"\n")
		b.WriteString("        trustForwardHeader: true\n")
		b.WriteString("        authResponseHeaders:\n")
		b.WriteString("          - X-authentik-username\n")
		b.WriteString("          - X-authentik-groups\n")
		b.WriteString("          - X-authentik-email\n")
		b.WriteString("          - X-authentik-name\n")
		b.WriteString("          - X-authentik-uid\n")
	}

	// Custom headers middleware (only if app has routing headers)
	if app.Routing != nil && len(app.Routing.Headers) > 0 {
		g.writeHeadersMiddleware(b, fmt.Sprintf("%s-headers", app.Name), app.Routing.Headers)
	}
}

// writeHeadersMiddleware writes a headers middleware with the given name and headers
func (g *Generator) writeHeadersMiddleware(b *strings.Builder, name string, headers map[string]string) {
	b.WriteString(fmt.Sprintf("    %s:\n", name))
	b.WriteString("      headers:\n")
	b.WriteString("        customResponseHeaders:\n")

	// Sort headers for deterministic output
	var headerNames []string
	for headerName := range headers {
		headerNames = append(headerNames, headerName)
	}
	sort.Strings(headerNames)

	for _, headerName := range headerNames {
		b.WriteString(fmt.Sprintf("          %s: \"%s\"\n", headerName, headers[headerName]))
	}
}

// writeOutpostRouter writes a high-priority router that passes /outpost.goauthentik.io/
// requests for a forward-auth app directly to the Authentik embedded outpost,
// bypassing the forward-auth middleware so the OAuth callback can complete.
func (g *Generator) writeOutpostRouter(b *strings.Builder, app *catalog.App) {
	hostRule := fmt.Sprintf("%s.%s", app.Name, g.baseDomain)
	b.WriteString(fmt.Sprintf("    %s-outpost:\n", app.Name))
	b.WriteString(fmt.Sprintf("      rule: \"Host(`%s`) && PathPrefix(`/outpost.goauthentik.io/`)\"\n", hostRule))
	b.WriteString("      service: authentik-outpost\n")
	b.WriteString("      priority: 15\n")
}

// writeService writes the service configuration for an app
func (g *Generator) writeService(b *strings.Builder, app *catalog.App) {
	b.WriteString(fmt.Sprintf("    %s:\n", app.Name))
	b.WriteString("      loadBalancer:\n")
	b.WriteString("        servers:\n")
	b.WriteString(fmt.Sprintf("          - url: \"http://localhost:%d\"\n", app.Port))
}

// Preview generates a preview of what the config will look like
func (g *Generator) Preview(apps []*catalog.App) string {
	return g.generateConfig(apps)
}
