// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"codeberg.org/d-buckner/bloud/cli/executor"
)

// The host-agent requires a credential for admin API calls even from a trusted
// position (loopback / BLOUD_TRUSTED_LOCAL_NETS): position is a scope, not a
// credential. The token is generated by the secrets manager and written to
// DataDirs.APITokenPath inside the runtime, so the CLI reads it from the guest
// through the backend's executor: the same seam that carries every other
// guest-side command.

// runtimeHost resolves the executor host for the selected backend.
func runtimeHost() (executor.Host, error) {
	bk, _, err := devBackend()
	if err != nil {
		return nil, err
	}
	return bk.Host(), nil
}

// readAPIToken reads the host-agent API credential from the runtime host.
func readAPIToken(ctx context.Context) (string, error) {
	host, err := runtimeHost()
	if err != nil {
		return "", err
	}

	tokenPath := host.DataDirs().APITokenPath()
	res, err := host.Executor().Run(ctx, executor.RunSpec{Command: "cat " + shellQuote(tokenPath)})
	if err != nil {
		return "", fmt.Errorf("reading API token (%s): %w", tokenPath, err)
	}
	if res.ExitCode != 0 {
		return "", fmt.Errorf("reading API token (%s): %s", tokenPath, strings.TrimSpace(res.Stderr))
	}

	token := strings.TrimSpace(res.Stdout)
	if token == "" {
		return "", errors.New("API token is empty: is the host-agent deployed? Run './bloud dev' first")
	}
	return token, nil
}

// authHeader renders the curl argument that carries the API credential. The
// value is shell-quoted: the command runs through a shell inside the guest.
func authHeader(token string) string {
	return "-H " + shellQuote("Authorization: Bearer "+token)
}

// apiTokenPath returns the credential path for the runtime this lifecycle
// deployed. The e2e runners choose their own --runtime-dir (default
// /var/tmp/bloud-e2e-runtime), which is not the native backend's default dir,
// so the path must come from the deployment rather than from devBackend().
func (r *lifecycle) apiTokenPath() string {
	return filepath.Join(r.cfg.remoteDir, "data", "host-agent-api-token")
}

// readAPITokenInRuntime reads the credential from the runtime this lifecycle
// deployed, through the same remote execution seam as every other guest command.
func (r *lifecycle) readAPITokenInRuntime() (string, error) {
	out, err := r.remoteOutput("cat " + shellQuote(r.apiTokenPath()))
	if err != nil {
		return "", fmt.Errorf("reading API token (%s): %w", r.apiTokenPath(), err)
	}
	token := strings.TrimSpace(out)
	if token == "" {
		return "", fmt.Errorf("API token is empty (%s). Is host-agent running?", r.apiTokenPath())
	}
	return token, nil
}

// apiTokenBestEffort reads this runtime's credential, warning (not failing) when
// it is unavailable: the e2e API helpers have their own fallback chain, and a
// Playwright-only run against an already-running runtime must not be blocked by
// a missing token file.
func (r *lifecycle) apiTokenBestEffort() string {
	token, err := r.readAPITokenInRuntime()
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not read the host-agent API token (%v); "+
			"e2e API helpers will fall back to BLOUD_E2E_RUNTIME_DIR or ./bloud token\n", err)
		return ""
	}
	return token
}

// cmdToken prints the runtime's host-agent API token, so other tooling (the
// Playwright helpers, ad-hoc curl) can authenticate the same way the CLI does.
func cmdToken() int {
	token, err := readAPIToken(context.Background())
	if err != nil {
		errorf("Could not read the host-agent API token: %v", err)
		return 1
	}
	fmt.Println(token)
	return 0
}
