// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Daniel Buckner

package main

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"codeberg.org/d-buckner/bloud/cli/executor"
)

// The host-agent requires a credential for admin API calls even from a trusted
// position (loopback / BLOUD_TRUSTED_LOCAL_NETS): position is a scope, not a
// credential. The token is generated by the secrets manager and written to
// DataDirs.APITokenPath inside the runtime, so the CLI reads it from the guest
// through the backend's executor — the same seam that carries every other
// guest-side command.

// runtimeHost resolves the executor host for the selected backend.
func runtimeHost() (executor.Host, error) {
	bk, _, err := devBackend()
	if err != nil {
		return nil, err
	}
	return bk.Host(), nil
}

// readAPIToken reads the host-agent API credential from the runtime host.
func readAPIToken(ctx context.Context) (string, error) {
	host, err := runtimeHost()
	if err != nil {
		return "", err
	}

	tokenPath := host.DataDirs().APITokenPath()
	res, err := host.Executor().Run(ctx, executor.RunSpec{Command: "cat " + shellQuote(tokenPath)})
	if err != nil {
		return "", fmt.Errorf("reading API token (%s): %w", tokenPath, err)
	}
	if res.ExitCode != 0 {
		return "", fmt.Errorf("reading API token (%s): %s", tokenPath, strings.TrimSpace(res.Stderr))
	}

	token := strings.TrimSpace(res.Stdout)
	if token == "" {
		return "", errors.New("API token is empty — is the host-agent deployed? Run './bloud dev' first")
	}
	return token, nil
}

// authHeader renders the curl argument that carries the API credential. The
// value is shell-quoted: the command runs through a shell inside the guest.
func authHeader(token string) string {
	return "-H " + shellQuote("Authorization: Bearer "+token)
}

// cmdToken prints the runtime's host-agent API token, so other tooling (the
// Playwright helpers, ad-hoc curl) can authenticate the same way the CLI does.
func cmdToken() int {
	token, err := readAPIToken(context.Background())
	if err != nil {
		errorf("Could not read the host-agent API token: %v", err)
		return 1
	}
	fmt.Println(token)
	return 0
}
