// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// The generated blocks in the README: the app list in `## catalog` and the
// strategy table in `## one login`. Both are derived from
// apps/*/metadata.yaml, the same source the dependency graph is drawn from,
// so adding an app updates the prose sections and the picture from one
// place. Both were typed by hand before this, and both went stale: the list
// was missing apps the catalog already shipped.
//
// The generated blocks carry no counts on purpose. A sentence that names how
// many apps there are is a second thing to keep in sync, and it is the one
// part of the section a reader does not need: the list is right below it.
const (
	catalogListBeginMarker = "<!-- BEGIN GENERATED CATALOG LIST -->"
	catalogListEndMarker   = "<!-- END GENERATED CATALOG LIST -->"
	loginTableBeginMarker  = "<!-- BEGIN GENERATED LOGIN TABLE -->"
	loginTableEndMarker    = "<!-- END GENERATED LOGIN TABLE -->"

	catalogDocDefaultFile = "README.md"
)

// generatedByLine is the in-block provenance note. The markers say where the
// block is; this says what writes it and that hand edits are lost, which is
// the one thing a reader standing in the middle of the block needs to know.
const generatedByLine = "<!-- Generated by `./bloud catalogdoc --write` from `apps/*/metadata.yaml`. Do not edit by hand. -->"

var (
	catalogListBlock = generatedBlock{
		Begin: catalogListBeginMarker,
		End:   catalogListEndMarker,
		Label: "catalog list",
	}
	loginTableBlock = generatedBlock{
		Begin: loginTableBeginMarker,
		End:   loginTableEndMarker,
		Label: "login table",
	}
)

// loginStrategyLabels is the README-facing name for each SSO strategy. The
// order of loginStrategyOrder is the order the rows are drawn in, so the
// table reads from the tightest integration to the loosest.
var loginStrategyLabels = map[string]string{
	"ldap":         "LDAP",
	"forward-auth": "Forward auth",
	"native-oidc":  "Native OIDC",
	"none":         "App-local accounts",
}

var loginStrategyOrder = []string{"ldap", "forward-auth", "native-oidc", "none"}

// loginQuirk overrides the strategy row an app is drawn under. It exists
// because `sso.strategy` describes how Bloud authenticates the app at the
// ingress, which is not always the answer the login table is being asked
// for: "what do I type into this app?"
//
// It is an override, deliberately kept here rather than in the app's
// metadata. The strategy enum is a runtime contract (invariant 6) and
// Seerr's value is correct for it: Seerr genuinely cannot delegate
// authentication. Only the README's grouping is wrong, so only the README
// generator carries the correction.
//
// The table is data, the same shape as the EXCEPTIONS table in
// scripts/pinned-images.mjs and the BASELINE block in
// scripts/file-length.mjs: every entry states the reason it exists, and
// checkLoginQuirks fails an entry that no longer changes anything, so the
// list cannot rot into a confident lie about a catalog that moved on.
type loginQuirk struct {
	app      string // catalog name of the app being overridden
	strategy string // strategy row to draw it under instead
	reason   string // why the declared strategy misdescribes the login
}

var loginQuirks = []loginQuirk{
	{
		app:      "seerr",
		strategy: "ldap",
		reason: "Seerr declares `none` because it cannot delegate authentication at the " +
			"ingress, but its users sign in with their Jellyfin account, and Jellyfin's " +
			"credential is LDAP-backed through Authentik. " +
			"\"App-local accounts\" tells a reader who already has a Bloud account that " +
			"they need something else. They do not.",
	},
}

// loginTableRowStrategy is the strategy row an app is drawn under: its own
// declared strategy, unless a quirk says that value misdescribes the login
// a reader would actually perform.
func loginTableRowStrategy(app *AppMetadata) string {
	if quirk, ok := findLoginQuirk(app.Name); ok {
		return quirk.strategy
	}
	return normalizeStrategy(app.SSO.Strategy)
}

// findLoginQuirk returns the override declared for an app, if any.
func findLoginQuirk(appName string) (loginQuirk, bool) {
	for _, quirk := range loginQuirks {
		if quirk.app == appName {
			return quirk, true
		}
	}
	return loginQuirk{}, false
}

// checkLoginQuirks returns every quirk that no longer describes the
// catalog. A quirk for an app that is gone, one that agrees with what the
// app already declares, and a second quirk for the same app are the same
// problem: the override is load-bearing for nothing, and a stale override
// is how a generated table starts lying without anyone editing it. An
// override that points at a strategy with no README label is caught here
// too, because a typo in this table renders a row no reader can map to a
// real mechanism.
func checkLoginQuirks(apps map[string]*AppMetadata) []string {
	var problems []string
	seen := make(map[string]bool, len(loginQuirks))

	for _, quirk := range loginQuirks {
		if seen[quirk.app] {
			problems = append(problems, fmt.Sprintf("duplicate quirk for %q", quirk.app))
		}
		seen[quirk.app] = true

		if strings.TrimSpace(quirk.reason) == "" {
			problems = append(problems, fmt.Sprintf("quirk for %q carries no reason", quirk.app))
		}
		if _, ok := loginStrategyLabels[quirk.strategy]; !ok {
			problems = append(problems, fmt.Sprintf("quirk for %q points at strategy %q, which has no README label",
				quirk.app, quirk.strategy))
		}

		app, ok := apps[quirk.app]
		if !ok {
			problems = append(problems, fmt.Sprintf("quirk names %q, which is not in the catalog", quirk.app))
			continue
		}
		if app.IsSystem {
			problems = append(problems, fmt.Sprintf("quirk for %q targets a system app, which the login table does not list", quirk.app))
			continue
		}
		if normalizeStrategy(app.SSO.Strategy) == quirk.strategy {
			problems = append(problems, fmt.Sprintf("quirk for %q sets strategy %q, which is what the app already declares: the override does nothing",
				quirk.app, quirk.strategy))
		}
	}
	return problems
}

// loginQuirkSummary names the overridden apps, so an override that changes
// what a reader sees is visible in the run that applied it rather than only
// in the diff that introduced it.
func loginQuirkSummary(apps map[string]*AppMetadata) string {
	if len(loginQuirks) == 0 {
		return ""
	}
	notes := make([]string, 0, len(loginQuirks))
	for _, quirk := range loginQuirks {
		app, ok := apps[quirk.app]
		if !ok {
			continue
		}
		notes = append(notes, fmt.Sprintf("%s renders under %s: %s",
			appDisplayName(app), loginStrategyLabel(quirk.strategy), quirk.reason))
	}
	if len(notes) == 0 {
		return ""
	}
	return strings.Join(notes, " ")
}

// catalogDocMode is what a `bloud catalogdoc` run does with the rendered
// blocks.
type catalogDocMode int

const (
	catalogDocPrint catalogDocMode = iota
	catalogDocWrite
	catalogDocCheck
	catalogDocHelp
)

// catalogDocSection pairs a block in the target document with the bytes the
// catalog produces for it right now.
type catalogDocSection struct {
	block     generatedBlock
	generated string
}

// catalogDocSections renders every generated section, in document order.
func catalogDocSections(apps map[string]*AppMetadata) []catalogDocSection {
	return []catalogDocSection{
		{block: catalogListBlock, generated: renderCatalogList(apps)},
		{block: loginTableBlock, generated: renderLoginTable(apps)},
	}
}

func cmdCatalogDoc(args []string) int {
	mode, target := parseCatalogDocArgs(args)
	if mode == catalogDocHelp {
		printCatalogDocUsage()
		return 0
	}
	if mode == catalogDocPrint && target == "" {
		// A bad flag was already reported; print is the zero value, so the
		// empty target is the "do not run" signal.
		return 1
	}

	root, err := getProjectRoot()
	if err != nil {
		errorf("Could not find project root: %v", err)
		return 1
	}

	apps, ok := loadCatalog(root)
	if !ok {
		return 1
	}
	if !reportLoginQuirks(apps, mode) {
		return 1
	}

	sections := catalogDocSections(apps)

	switch mode {
	case catalogDocWrite:
		return writeCatalogDoc(root, target, sections)
	case catalogDocCheck:
		return checkCatalogDoc(root, target, sections)
	default:
		for i, section := range sections {
			if i > 0 {
				fmt.Println()
			}
			fmt.Print(section.generated)
		}
		return 0
	}
}

// parseCatalogDocArgs reads the flag list. An unrecognised or malformed flag
// comes back as print with an empty target, which cmdCatalogDoc reads as
// "already reported, do not run": the error text belongs next to the flag
// that caused it, not at each return.
func parseCatalogDocArgs(args []string) (catalogDocMode, string) {
	mode := catalogDocPrint
	target := catalogDocDefaultFile
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--write":
			mode = catalogDocWrite
		case "--check":
			mode = catalogDocCheck
		case "--target":
			if i+1 >= len(args) {
				errorf("--target needs a path (usage: bloud catalogdoc [--write | --check] [--target FILE])")
				return catalogDocPrint, ""
			}
			i++
			target = args[i]
		case "--help", "-h":
			return catalogDocHelp, ""
		default:
			errorf("Unknown flag %q (usage: bloud catalogdoc [--write | --check] [--target FILE])", args[i])
			return catalogDocPrint, ""
		}
	}
	return mode, target
}

// reportLoginQuirks validates the QUIRKS override against the catalog and,
// in the modes that produce a document rather than the raw blocks, prints
// what the override is doing. Returns false when the override is out of
// step, which stops both --write and --check rather than letting either one
// ship a table built from a stale assertion.
func reportLoginQuirks(apps map[string]*AppMetadata, mode catalogDocMode) bool {
	if problems := checkLoginQuirks(apps); len(problems) > 0 {
		errorf("the login table QUIRKS override is out of step with the catalog:\n  - %s",
			strings.Join(problems, "\n  - "))
		return false
	}
	if mode == catalogDocPrint {
		return true
	}
	if summary := loginQuirkSummary(apps); summary != "" {
		log("Login table overrides: " + summary)
	}
	return true
}

// printCatalogDocUsage documents the catalogdoc command's modes.
func printCatalogDocUsage() {
	fmt.Println("Usage: bloud catalogdoc [--write | --check] [--target FILE]")
	fmt.Println()
	fmt.Println("  (no flags)   Print the generated catalog list and login table")
	fmt.Println("  --write      Replace both generated blocks in the target file")
	fmt.Println("  --check      Exit 1 when either block is not what the catalog")
	fmt.Println("               produces right now (the PR-time gate)")
	fmt.Println("  --target     File to write or check (default: " + catalogDocDefaultFile + ")")
}

// writeCatalogDoc splices every generated block into the target in one pass
// over the file. It fails rather than appending when a block's markers are
// missing, so a typo in the target can never produce a second copy of the
// generated content.
func writeCatalogDoc(root, target string, sections []catalogDocSection) int {
	path := docTargetPath(root, target)
	content, err := os.ReadFile(path)
	if err != nil {
		errorf("Could not read %s: %v", path, err)
		return 1
	}

	updated := string(content)
	changed := false
	for _, section := range sections {
		next, ok := section.block.Splice(updated, section.generated)
		if !ok {
			errorf("%s", section.block.missingBlockMessage(relOrAbs(root, path)))
			return 1
		}
		if next != updated {
			updated = next
			changed = true
		}
	}

	if !changed {
		log(relOrAbs(root, path) + " catalog sections are already current")
		return 0
	}
	if err := os.WriteFile(path, []byte(updated), 0644); err != nil {
		errorf("Could not write %s: %v", path, err)
		return 1
	}
	log("Wrote the catalog sections to " + relOrAbs(root, path))
	return 0
}

// checkCatalogDoc compares each generated block against what the catalog
// produces now. A stale README describes apps that no longer exist, or omits
// apps that do, so this is the gate that keeps the two together.
func checkCatalogDoc(root, target string, sections []catalogDocSection) int {
	path := docTargetPath(root, target)
	content, err := os.ReadFile(path)
	if err != nil {
		errorf("Could not read %s: %v", path, err)
		return 1
	}

	var stale []catalogDocSection
	for _, section := range sections {
		existing, ok := section.block.Extract(string(content))
		if !ok {
			errorf("%s has no generated %s block. Run: ./bloud catalogdoc --write",
				relOrAbs(root, path), section.block.Label)
			return 1
		}
		if !section.block.Same(existing, section.generated) {
			stale = append(stale, section)
		}
	}

	if len(stale) > 0 {
		labels := make([]string, 0, len(stale))
		for _, section := range stale {
			labels = append(labels, section.block.Label)
		}
		errorf("%s is out of date with the catalog (%s). Run: ./bloud catalogdoc --write (then commit the result)",
			relOrAbs(root, path), strings.Join(labels, ", "))
		for _, section := range stale {
			existing, _ := section.block.Extract(string(content))
			section.block.ReportDifference(existing, section.generated)
		}
		return 1
	}

	log(relOrAbs(root, path) + " catalog sections are up to date")
	return 0
}

// renderCatalogList renders the generated part of the `## catalog` section:
// one bullet per user app, then the system apps the catalog needs to run
// itself. System apps are listed apart rather than in the same bullets
// because a reader cannot install them and would not want to.
func renderCatalogList(apps map[string]*AppMetadata) string {
	userApps, systemApps := splitCatalog(apps)

	var sb strings.Builder
	sb.WriteString(catalogListBeginMarker + "\n")
	sb.WriteString(generatedByLine + "\n")
	for _, app := range userApps {
		sb.WriteString(catalogBullet(app))
	}
	sb.WriteString("\n" + systemAppsLine(systemApps) + "\n")
	sb.WriteString(catalogListEndMarker + "\n")
	return sb.String()
}

// catalogBullet is one app's bullet: its display name and the one-line
// description it already carries in metadata.yaml. An app with no
// description is listed by name alone rather than with an empty clause.
func catalogBullet(app *AppMetadata) string {
	name := appDisplayName(app)
	description := strings.TrimSpace(app.Description)
	if description == "" {
		return fmt.Sprintf("- **%s**\n", name)
	}
	return fmt.Sprintf("- **%s**: %s\n", name, description)
}

// systemAppsLine names the system apps with their catalog category, so the
// line says what each one is for without a hand-maintained role table.
func systemAppsLine(systemApps []*AppMetadata) string {
	if len(systemApps) == 0 {
		return "Bloud ships no system apps."
	}
	roles := make([]string, 0, len(systemApps))
	for _, app := range systemApps {
		role := strings.TrimSpace(app.Category)
		if role == "" {
			role = "infrastructure"
		}
		roles = append(roles, fmt.Sprintf("**%s** (%s)", appDisplayName(app), role))
	}
	return "Plus the system apps: " + joinEnglish(roles) + "."
}

// renderLoginTable renders the `## one login` table: every user app under
// the login strategy it declares, with the QUIRKS overrides applied. Apps
// with no declared strategy land in the `none` row, which is what the
// catalog means by it: the app keeps its own credential end to end.
func renderLoginTable(apps map[string]*AppMetadata) string {
	userApps, _ := splitCatalog(apps)

	byStrategy := make(map[string][]string)
	for _, app := range userApps {
		strategy := loginTableRowStrategy(app)
		byStrategy[strategy] = append(byStrategy[strategy], appDisplayName(app))
	}

	var sb strings.Builder
	sb.WriteString(loginTableBeginMarker + "\n")
	sb.WriteString(generatedByLine + "\n")
	sb.WriteString("| Strategy | Apps |\n")
	sb.WriteString("|---|---|\n")
	for _, strategy := range orderedStrategies(byStrategy) {
		fmt.Fprintf(&sb, "| **%s** | %s |\n", loginStrategyLabel(strategy), strings.Join(byStrategy[strategy], ", "))
	}
	sb.WriteString(loginTableEndMarker + "\n")
	return sb.String()
}

// normalizeStrategy maps an undeclared strategy onto `none`. The catalog
// treats a user app with no `sso.strategy` as one that never joins the
// identity provider, which is the same thing `none` says.
func normalizeStrategy(strategy string) string {
	strategy = strings.TrimSpace(strategy)
	if strategy == "" {
		return "none"
	}
	return strategy
}

// orderedStrategies returns the strategies present in the catalog: the known
// ones in the documented order, then anything else alphabetically. A strategy
// this command does not know still gets a row, so a new one shows up in the
// README instead of being dropped from it.
func orderedStrategies(byStrategy map[string][]string) []string {
	known := make([]string, 0, len(loginStrategyOrder))
	seen := make(map[string]bool, len(loginStrategyOrder))
	for _, strategy := range loginStrategyOrder {
		if len(byStrategy[strategy]) > 0 {
			known = append(known, strategy)
			seen[strategy] = true
		}
	}

	unknown := make([]string, 0, len(byStrategy))
	for strategy := range byStrategy {
		if !seen[strategy] {
			unknown = append(unknown, strategy)
		}
	}
	sort.Strings(unknown)

	return append(known, unknown...)
}

// loginStrategyLabel is the README-facing name for a strategy, falling back
// to a humanized form of the raw value for a strategy this command has never
// seen.
func loginStrategyLabel(strategy string) string {
	if label, ok := loginStrategyLabels[strategy]; ok {
		return label
	}
	return humanize(strategy)
}

// humanize turns a catalog identifier into words: dashes and underscores
// become spaces, and the first letter is capitalized.
func humanize(identifier string) string {
	words := strings.NewReplacer("-", " ", "_", " ").Replace(identifier)
	if words == "" {
		return words
	}
	return strings.ToUpper(words[:1]) + words[1:]
}

// splitCatalog splits the catalog into user apps and system apps, each
// sorted by display name so the generated list reads alphabetically the way
// a hand-written one would.
func splitCatalog(apps map[string]*AppMetadata) (userApps, systemApps []*AppMetadata) {
	for _, app := range apps {
		if app.IsSystem {
			systemApps = append(systemApps, app)
		} else {
			userApps = append(userApps, app)
		}
	}
	sortApps(userApps)
	sortApps(systemApps)
	return userApps, systemApps
}

// sortApps orders apps case-insensitively by display name, which puts
// "qBittorrent" where a reader looks for it rather than after every capital.
func sortApps(apps []*AppMetadata) {
	sort.Slice(apps, func(i, j int) bool {
		left, right := appDisplayName(apps[i]), appDisplayName(apps[j])
		if !strings.EqualFold(left, right) {
			return strings.ToLower(left) < strings.ToLower(right)
		}
		return apps[i].Name < apps[j].Name
	})
}

// joinEnglish joins a list with commas and a final "and".
func joinEnglish(items []string) string {
	switch len(items) {
	case 0:
		return ""
	case 1:
		return items[0]
	case 2:
		return items[0] + " and " + items[1]
	default:
		return strings.Join(items[:len(items)-1], ", ") + ", and " + items[len(items)-1]
	}
}
