// SPDX-License-Identifier: AGPL-3.0-only

package main

import (
	"fmt"
	"strings"
)

// renderDependencyGraph renders the whole catalog as one mermaid diagram: a
// box per app, one node per container inside that box, the within-app
// dependsOn arrows, and the cross-app integration arrows.
//
// It mirrors the developer dashboard's graph (the developer graph in
// internal/api/system_module.go), which draws the same app boxes holding
// their container nodes with the same edge labels, so the README and the
// dashboard describe one topology rather than two that can drift.
func renderDependencyGraph(apps map[string]*AppMetadata) string {
	var sb strings.Builder

	sb.WriteString(graphBeginMarker + "\n")
	sb.WriteString("<!-- Generated by `./bloud depgraph --write` from `apps/*/metadata.yaml`. Do not edit by hand. -->\n")
	sb.WriteString("\n")
	sb.WriteString("```mermaid\n")
	sb.WriteString("flowchart TD\n")

	ids := assignContainerIDs(apps)
	for _, appName := range sortedAppNames(apps) {
		sb.WriteString(renderAppBox(apps[appName], ids))
	}

	// Drawn outside every box: the instance provides it, not an app.
	fmt.Fprintf(&sb, "\n    %s[\"%s\"]\n", settingProviderMermaid, settingProviderLabel)

	sb.WriteString("\n    %% Cross-app integration edges\n")
	for _, edge := range integrationEdges(apps) {
		fmt.Fprintf(&sb, "    %s -->|%s| %s\n",
			edgeEnd(edge.from), edge.label, edgeEnd(edge.to))
	}

	sb.WriteString("```\n")
	sb.WriteString("\n" + graphLegend + "\n")
	sb.WriteString(graphEndMarker + "\n")
	return sb.String()
}

// graphLegend explains the notation, because the diagram is generated and no
// prose around it is written by whoever changed the metadata.
const graphLegend = "_Each box is one app; the nodes inside it are that app's containers, with an arrow from a container to every container it depends on. " +
	"Arrows between boxes are integrations: a `proxy` arrow is drawn from the proxy to the apps it routes, and an SSO arrow is labeled with the app's strategy (`ldap`, `forward-auth`, `native-oidc`). " +
	"The AI Model node is outside every box because no app provides it: it is the instance's own Settings -> AI endpoint, and any app that declares the `inference` contract is wired to it._"

// appDisplayName is the app's display name, falling back to its catalog id.
func appDisplayName(app *AppMetadata) string {
	if app.DisplayName != "" {
		return app.DisplayName
	}
	return app.Name
}

// appBoxTitle is the mermaid box title: the display name, with system apps
// labeled so the infrastructure the rest depends on reads as infrastructure.
func appBoxTitle(app *AppMetadata) string {
	title := appDisplayName(app)
	if app.IsSystem {
		title += " (system)"
	}
	return title
}

// renderAppBox renders one app: its titled box, a node per container, and
// the dependsOn arrows between them.
func renderAppBox(app *AppMetadata, ids *containerIDs) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "\n    subgraph %s[\"%s\"]\n", appBoxID(app.Name), appBoxTitle(app))

	if len(app.Containers) == 0 {
		// An app that declares no containers is one node, the way the
		// lifecycle graph names it after its catalog entry.
		fmt.Fprintf(&sb, "        %s[\"%s\"]\n", ids.get(app.Name, app.Name), app.Name)
		sb.WriteString("    end\n")
		return sb.String()
	}

	for _, container := range app.Containers {
		fmt.Fprintf(&sb, "        %s[\"%s\"]\n",
			ids.get(app.Name, container.Name), containerLabel(container.Name, app.Name))
	}
	for _, container := range app.Containers {
		for _, dep := range container.DependsOn {
			if !appDeclaresContainer(app, dep) {
				continue
			}
			fmt.Fprintf(&sb, "        %s --> %s\n",
				ids.get(app.Name, container.Name), ids.get(app.Name, dep))
		}
	}
	sb.WriteString("    end\n")
	return sb.String()
}
