{ config, pkgs, lib, ... }:

let
  mkNativeApp = import ../../nixos/lib/native-app.nix { inherit config pkgs lib; };
in
mkNativeApp {
  name = "traefik";
  description = "Traefik reverse proxy";
  port = 8080;
  serviceName = "traefik";
  # Traefik has no configurator — no runtime secrets or config injection needed
  configuratorHooks = false;
  options = {
    apiPort = {
      type = lib.types.int;
      default = 3000;
      description = "Port for the host-agent API backend";
    };
    uiPort = {
      type = lib.types.int;
      default = 5173;
      description = "Port for the Bloud UI (Vite dev server)";
    };
  };

  nixosConfig = cfg: {
    services.traefik = {
      enable = true;
      staticConfigOptions = {
        entryPoints.web.address = ":${toString cfg.port}";
        providers.file = {
          directory = "/var/lib/traefik/dynamic/";
          watch = true;
        };
        api.dashboard = true;
        ping.entryPoint = "web";
        log.level = "DEBUG";
      };
    };

    # Add bloud user to traefik group so host-agent can write to the dynamic config dir.
    users.users.${cfg.bloudUser}.extraGroups = [ "traefik" ];

    # Dynamic config directory with setgid: new files inherit the traefik group.
    # bloud user (in traefik group, mode 2775) can write; traefik service can read.
    systemd.tmpfiles.rules = [
      "d /var/lib/traefik/dynamic 2775 traefik traefik -"
    ];

    # Write static dynamic config files atomically on every NixOS activation.
    # IMPORTANT: Use atomic writes (write to .tmp, then mv) to prevent Traefik
    # from seeing truncated files during config reload.
    # base.yml: static routes — UI, API, dashboard, common middlewares.
    # apps-routes.yml: managed by host-agent traefikgen at runtime; only create
    # placeholder on first activation, never overwrite an existing file.
    system.activationScripts.bloud-traefik-config = lib.stringAfter [ "users" ] ''
      mkdir -p /var/lib/traefik/dynamic
      chown traefik:traefik /var/lib/traefik/dynamic
      chmod 2775 /var/lib/traefik/dynamic

      cat > /var/lib/traefik/dynamic/base.yml.tmp <<'EOF'
http:
  routers:
    # Traefik dashboard (access via /dashboard/)
    traefik-dashboard:
      rule: "PathPrefix(`/dashboard`)"
      service: api@internal
      priority: 95

    # Host agent API
    host-api:
      rule: "PathPrefix(`/api`)"
      service: host-agent
      priority: 90

    # Host agent auth routes (OAuth login/callback/logout)
    host-auth:
      rule: "PathPrefix(`/auth`)"
      service: host-agent
      priority: 89

    # Authentik outpost endpoints (for OAuth start/callback flows)
    # Traefik adds X-Forwarded-* headers which the outpost needs to match providers
    authentik-outpost:
      rule: "PathPrefix(`/outpost.goauthentik.io`)"
      service: authentik-outpost
      priority: 85

    # Bloud UI (catch-all, handles /{appname} routes internally)
    bloud-ui:
      rule: "PathPrefix(`/`)"
      middlewares:
        - cross-origin-isolation
      service: bloud-ui
      priority: 1

  middlewares:
    # Cross-origin isolation headers for SharedArrayBuffer support
    # 'credentialless' enables SharedArrayBuffer while being more permissive than 'require-corp'
    cross-origin-isolation:
      headers:
        customResponseHeaders:
          Cross-Origin-Opener-Policy: "same-origin"
          Cross-Origin-Embedder-Policy: "credentialless"

    # Common middleware for iframe embedding - removes restrictive headers from apps
    iframe-headers:
      headers:
        customResponseHeaders:
          X-Frame-Options: ""
          Content-Security-Policy: ""

    # Embed isolation headers - matches parent page COOP/COEP
    embed-isolation:
      headers:
        customResponseHeaders:
          Cross-Origin-Opener-Policy: "same-origin"
          Cross-Origin-Embedder-Policy: "credentialless"

    # Forward headers for embedded apps - ensures apps know their public URL
    # This is critical for apps like Jellyfin that need to return correct
    # LocalAddress in API responses to avoid "server mismatch" warnings
    embed-forwarded-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Host: "localhost:${toString cfg.port}"
          X-Forwarded-Proto: "http"

  services:
    host-agent:
      loadBalancer:
        servers:
          - url: "http://localhost:${toString cfg.apiPort}"

    bloud-ui:
      loadBalancer:
        servers:
          - url: "http://localhost:${toString cfg.uiPort}"

    # Authentik server (serves outpost endpoints via embedded outpost)
    authentik-outpost:
      loadBalancer:
        servers:
          - url: "http://localhost:9001"
EOF
      mv /var/lib/traefik/dynamic/base.yml.tmp /var/lib/traefik/dynamic/base.yml
      chown traefik:traefik /var/lib/traefik/dynamic/base.yml

      # App routes (generated by host-agent traefikgen)
      # Create empty placeholder if not exists (atomic write)
      if [ ! -f /var/lib/traefik/dynamic/apps-routes.yml ]; then
        cat > /var/lib/traefik/dynamic/apps-routes.yml.tmp <<'EOF'
# Generated by Bloud - DO NOT EDIT MANUALLY
# This file is managed by the Bloud host agent
# Traefik watches this file for changes

# No routable apps installed yet
EOF
        mv /var/lib/traefik/dynamic/apps-routes.yml.tmp /var/lib/traefik/dynamic/apps-routes.yml
        chown traefik:traefik /var/lib/traefik/dynamic/apps-routes.yml
      fi
    '';
  };
}
