# Native NixOS configuration for Proxmox VM development
#
# Full development environment for running Bloud directly on a Proxmox VM.
# Develop via SSH or VS Code Remote. Host-agent is compiled on the server.
#
# Prerequisites:
#   - NixOS installed on Proxmox VM (any standard install works)
#   - SSH access to the VM
#
# Deployment:
#   1. Clone repo to the VM
#   2. Build host-agent: cd services/host-agent && go build -o /tmp/host-agent ./cmd/host-agent
#   3. Apply config: sudo nixos-rebuild switch --flake .#dev-server --impure
#
# The --impure flag is needed to import /etc/nixos/hardware-configuration.nix

{ config, pkgs, lib, modulesPath, ... }:

{
  imports = [
    # Import the system's hardware config (filesystems, kernel modules)
    # This is generated by nixos-generate-config during install
    /etc/nixos/hardware-configuration.nix
  ]
  # Import generated config from either:
  # 1. Project's generated/ directory (for testing with git)
  # 2. User's data directory (for API-generated config)
  ++ lib.optional (builtins.pathExists ./generated/apps.nix) ./generated/apps.nix
  ++ lib.optional (builtins.pathExists /home/bloud/.local/share/bloud/nix/apps.nix) /home/bloud/.local/share/bloud/nix/apps.nix;

  # QEMU guest agent for Proxmox integration (shutdown, snapshots, etc.)
  services.qemuGuest.enable = true;

  # Boot loader - defaults to BIOS/GRUB on /dev/sda (common for Proxmox)
  # Override in a local config if using EFI or different disk
  boot.loader.grub.enable = lib.mkDefault true;
  boot.loader.grub.device = lib.mkDefault "/dev/sda";

  # Network configuration
  networking = {
    hostName = "bloud";  # Will be bloud.local via mDNS
    useDHCP = true;

    # Open firewall for all bloud services
    firewall = {
      enable = true;
      allowedTCPPorts = [
        22    # SSH
        53    # DNS (redirects to 5353)
        80    # HTTP (redirects to 8080)
        3000  # Host Agent API
        5173  # Vite Dev Server
        8080  # Traefik (main entry point)
        8081  # Traefik additional
        8082  # Traefik additional
        8085  # Miniflux direct
        9001  # Authentik
        9443  # Authentik HTTPS
        5006  # Actual Budget direct
        9999  # Dev server API (if enabled)
      ];
      allowedUDPPorts = [
        53    # DNS (redirects to 5353)
      ];
    };

  };

  # Redirect privileged ports to unprivileged ports (rootless containers)
  # Port 80 -> 8080 (Traefik)
  # Port 53 -> 5353 (AdGuard DNS)
  networking.firewall.extraCommands = ''
    iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
    iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-port 5353
    iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-port 5353
  '';
  networking.firewall.extraStopCommands = ''
    iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080 || true
    iptables -t nat -D PREROUTING -p tcp --dport 53 -j REDIRECT --to-port 5353 || true
    iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-port 5353 || true
  '';

  # Bloud user - dedicated service user
  users.users.bloud = {
    isNormalUser = true;
    description = "Bloud development user";
    extraGroups = [ "wheel" "podman" ];
    # Default password for initial setup (change via passwd)
    initialPassword = "bloud";
    # Enable lingering so user services start at boot
    linger = true;

    # SSH key authentication - add your public key here
    openssh.authorizedKeys.keys = [
      # Add your SSH public key(s) here, e.g.:
      # "ssh-ed25519 AAAA... user@host"
    ];
  };

  # System service to start user services after boot
  # Uses machinectl to properly trigger the user's systemd instance
  systemd.services.bloud-user-services = {
    description = "Start Bloud user services";
    wantedBy = [ "multi-user.target" ];
    after = [ "systemd-user-sessions.service" "user@1000.service" "network-online.target" ];
    wants = [ "network-online.target" ];
    requires = [ "user@1000.service" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeShellScript "start-bloud-user-services" ''
        # Reload and start bloud apps target via machinectl
        ${pkgs.systemd}/bin/machinectl shell bloud@ /run/current-system/sw/bin/systemctl --user daemon-reload || true
        ${pkgs.systemd}/bin/machinectl shell bloud@ /run/current-system/sw/bin/systemctl --user start bloud-apps.target || true
      '';
      # Re-run on rebuild to pick up new services
      ExecReload = pkgs.writeShellScript "reload-bloud-user-services" ''
        ${pkgs.systemd}/bin/machinectl shell bloud@ /run/current-system/sw/bin/systemctl --user daemon-reload || true
        ${pkgs.systemd}/bin/machinectl shell bloud@ /run/current-system/sw/bin/systemctl --user restart bloud-apps.target || true
      '';
    };
  };

  # Enable passwordless sudo for bloud user (needed for nixos-rebuild)
  security.sudo.extraRules = [
    {
      users = [ "bloud" ];
      commands = [
        {
          command = "ALL";
          options = [ "NOPASSWD" ];
        }
      ];
    }
  ];

  # SSH server
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = true;  # For initial setup, disable after adding SSH keys
    };
  };

  # VS Code Remote SSH support
  # This auto-patches VS Code server binaries for NixOS compatibility
  services.vscode-server.enable = true;
  services.vscode-server.enableFHS = true;  # Use FHS environment for better compatibility

  # mDNS for bloud.local resolution
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish = {
      enable = true;
      addresses = true;
    };
  };

  # Bloud infrastructure
  bloud = {
    enable = true;
    user = "bloud";
    agentPath = "/tmp/host-agent";  # Build with: go build -o /tmp/host-agent ./cmd/host-agent
    externalHost = "http://bloud.local";
    authentikExternalHost = "http://bloud.local";
  };

  # Nix settings - enable flakes
  nix = {
    settings = {
      experimental-features = [ "nix-command" "flakes" ];
      trusted-users = [ "root" "bloud" ];
    };
  };

  # Development packages
  environment.systemPackages = with pkgs; [
    # Dev tools
    go
    air            # Go hot reload
    nodejs_22      # Node.js for Vite/frontend
    tmux           # Session management
    git
    vim
    htop
    jq
    curl
    wget

    # Debugging
    lsof
    netcat
    tcpdump

    # Claude Code CLI wrapper (actual install via npm)
    (writeShellScriptBin "claude" ''
      # Ensure Claude Code is installed
      if ! command -v ${pkgs.nodejs_22}/bin/npx &> /dev/null; then
        echo "Node.js not available"
        exit 1
      fi
      exec ${pkgs.nodejs_22}/bin/npx -y @anthropic-ai/claude-code@latest "$@"
    '')
  ];

  # Git configuration - mark mounted directories as safe
  environment.etc."gitconfig".text = ''
    [safe]
      directory = *
  '';

  # System state version
  system.stateVersion = "24.11";
}
