# Bloud Installed System
#
# NixOS configuration applied by the Bloud installer to the target disk.
# The installer runs: nixos-install --flake <pkg>/share/bloud-installer/bloud#bloud
#
# Disk layout (created by services/installer/internal/partition/partition.go):
#   Partition 1 → BIOS boot (1MiB–2MiB, bios_grub type, no filesystem)
#   Partition 2 → label "ESP"   → /boot (FAT32, EFI)
#   Partition 3 → label "nixos" → /     (ext4)

{ config, pkgs, lib, ... }:

{
  imports = [
    ./modules/host-agent.nix
  ]
  # Load app config generated by host-agent (requires nixos-rebuild --impure)
  ++ lib.optional (builtins.pathExists /home/bloud/.local/share/bloud/nix/apps.nix)
       /home/bloud/.local/share/bloud/nix/apps.nix;

  # QEMU guest agent for Proxmox IP detection and lifecycle management
  services.qemuGuest.enable = true;

  # Boot: hybrid GRUB — installs to both MBR (BIOS boot) and EFI partition.
  # This supports SeaBIOS (test VMs) and UEFI firmware (real hardware) with one image.
  # Requires: GPT disk with a 1MiB BIOS boot partition (type bios_grub) + FAT32 EFI partition.
  boot.loader.grub.enable = true;
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.efiInstallAsRemovable = true;
  boot.loader.grub.device = "/dev/sda";  # Install BIOS GRUB to MBR/BIOS-boot-partition
  boot.loader.timeout = 3;

  # Kernel modules for virtio hardware (Proxmox/QEMU)
  boot.initrd.availableKernelModules = [
    "virtio_pci"
    "virtio_blk"
    "virtio_scsi"
    "virtio_net"
  ];

  # Filesystems — labels set by the installer's partition step
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/ESP";
    fsType = "vfat";
  };

  # Network
  networking = {
    hostName = "bloud";
    useDHCP = true;

    firewall = {
      enable = true;
      allowedTCPPorts = [
        22    # SSH
        80    # HTTP (iptables redirects to Traefik on 8080)
        3000  # Host Agent API
        8080  # Traefik (main entry point)
      ];
    };

    # Redirect port 80 → Traefik 8080 (rootless containers can't bind privileged ports)
    firewall.extraCommands = ''
      iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
    '';
    firewall.extraStopCommands = ''
      iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080 || true
    '';
  };

  # bloud user — runs app containers and host-agent
  users.users.bloud = {
    isNormalUser = true;
    extraGroups = [ "wheel" "podman" ];
    # Default password for initial access; changed via setup wizard post-install
    initialPassword = "bloud";
    # Enable lingering so user services start at boot without a login session
    linger = true;
  };

  # System service to start bloud user services after boot
  systemd.services.bloud-user-services = {
    description = "Start Bloud user services";
    wantedBy = [ "multi-user.target" ];
    after = [ "systemd-user-sessions.service" "user@1000.service" "network-online.target" ];
    wants = [ "network-online.target" ];
    requires = [ "user@1000.service" ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStart = pkgs.writeShellScript "start-bloud-user-services" ''
        ${pkgs.systemd}/bin/machinectl shell bloud@ /run/current-system/sw/bin/systemctl --user daemon-reload || true
        ${pkgs.systemd}/bin/machinectl shell bloud@ /run/current-system/sw/bin/systemctl --user start bloud-apps.target || true
      '';
      ExecReload = pkgs.writeShellScript "reload-bloud-user-services" ''
        ${pkgs.systemd}/bin/machinectl shell bloud@ /run/current-system/sw/bin/systemctl --user daemon-reload || true
        ${pkgs.systemd}/bin/machinectl shell bloud@ /run/current-system/sw/bin/systemctl --user restart bloud-apps.target || true
      '';
    };
  };

  # Passwordless sudo for bloud user (nixos-rebuild, service management)
  security.sudo.extraRules = [
    {
      users = [ "bloud" ];
      commands = [{
        command = "ALL";
        options = [ "NOPASSWD" ];
      }];
    }
  ];

  # SSH
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = true;
    };
  };

  # mDNS so browsers can reach http://bloud.local after install
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    publish = {
      enable = true;
      addresses = true;
    };
  };

  # Bloud infrastructure (options defined in bloud.nix, imported via flake)
  bloud = {
    enable = true;
    user = "bloud";
    externalHost = "http://bloud.local";
    authentikExternalHost = "http://bloud.local";
  };

  # Host agent — app management API and web UI
  bloud."host-agent" = {
    enable = true;
    flakeTarget = "bloud";
  };

  # Postgres — host-agent uses this as its database
  bloud.apps.postgres.enable = true;

  # Traefik — routes / to host-agent, proxies app UIs
  bloud.apps.traefik = {
    enable = true;
    port = 8080;
    apiPort = 3000;
  };

  # Nix settings (needed for nixos-rebuild post-install)
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    trusted-users = [ "root" "bloud" ];
  };

  environment.systemPackages = with pkgs; [
    curl
    jq
  ];

  system.stateVersion = "24.11";
}
